appium/java-client

src/main/java/io/appium/java_client/remote/MobileCapabilityType.java
How do you feel about adding the following sauce-specific Capability?
If we merge this, we're totally fine with merging other custom capabilities supplied by other Appium hosting services ^.^
@TikhomirovSergey and @bootstraponline
=> added APPIUM_VERSION MobileCapabilityType

pom.xml, src/test/java/io/appium/java_client/pagefactory_tests/DesctopBrowserCompatibilityTest.java
- Update to Selenium 2.45.0.
- Fix of MobileBrowserCompatibilityTest
=> Minor improvements. Update & Fix

src/main/java/io/appium/java_client/AppiumDriver.java, src/main/java/io/appium/java_client/generic/searchcontext/GenericFindsByLinkText.java, src/main/java/io/appium/java_client/generic/searchcontext/GenericFindsByTagName.java
Change list:
- The method declaration of __GenericFindsByLinkText__ and __GenericFindsByTagName__ interfaces was improved
- The scrolling methods declaration of AppiumDriver was improved
=> Minor improvements of the method declaration

src/main/java/io/appium/java_client/service/local/flags/GeneralServerFlag.java
=> Fix missing dashes in server flag

README.md
see https://github.com/appium/java-client/issues/133  and https://github.com/appium/java-client/commit/4f5c57ec936a7c162455016c7e1642a25f423cc7
=> setValue moved to iOSElement not AndroidElement

README.md
it would also be great to have a proper example how this can be harnessed in practice. I couldn't find anything on this topic.
=> Fixed Typo getAppString-> getAppStrings

README.md, src/main/java/io/appium/java_client/AppiumDriver.java, src/main/java/io/appium/java_client/DeviceActionShortcuts.java, src/main/java/io/appium/java_client/MobileCommand.java, src/test/java/io/appium/java_client/android/AndroidDriverTest.java, src/test/java/io/appium/java_client/ios/IOSDriverTest.java
#296 @TikhomirovSergey @imurchie @Jonahss please review
=> "getDeviceTime" function implementation

src/main/java/io/appium/java_client/AppiumDriver.java, src/main/java/io/appium/java_client/android/AndroidDriver.java
@TikhomirovSergey @imurchie @Jonahss please review it's minor fix, but in current version long press work incorrect.
=> Fix end point for longPressKeyCode and fix method implementation

README.md, pom.xml
@TikhomirovSergey @Jonahss Please review
=> Updated README.md

README.md
Old link is archived, this will point to exact one drafted in Selenium
##Details
Old link is archived, this will point to exact link which is drafted in Selenium repo
=> Updated Mobile JSON Wire Protocol Link

pom.xml
=> the addition to #369

pom.xml
@TikhomirovSergey @SrinivasanTarget 
- [x ] New feature (non-breaking change which adds functionality)
##Details
CVSS - Common Vulnerability Scoring System i set to 7, which means if any High Vulnerabilities found the build would fail.
=> Added support for dependency check

src/main/java/io/appium/java_client/ios/IOSElement.java
Removed the duplicate ScrollTo Method.
This got introduced here:
https://github.com/appium/java-client/commit/92474a1f028dfb438d179e4c81eac7100abc1000
Seems some latest merge introduced a duplicate method here:https://github.com/appium/java-client/commit/92474a1f028dfb438d179e4c81eac7100abc1000
@TikhomirovSergey please merge this.
=> Removed the duplicate ScrollTo Method

src/main/java/io/appium/java_client/android/AndroidDriver.java, src/main/java/io/appium/java_client/android/PushesFiles.java, src/test/java/io/appium/java_client/android/AndroidDriverTest.java
The additional method pushFile(remotePath,  file)
It is the minor change
This method was added for the sake of user's convenience.
=> The additional method pushFile(remotePath,  file)

src/main/java/io/appium/java_client/android/AndroidDriver.java, src/main/java/io/appium/java_client/ios/IOSDriver.java, src/main/java/io/appium/java_client/ios/IOSElement.java, src/main/java/io/appium/java_client/pagefactory/bys/ContentMappedBy.java, src/main/java/io/appium/java_client/pagefactory/bys/builder/Strategies.java
Minor code fixes
@TikhomirovSergey Please review.
=> Minor code fixes

src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java
Added appWaitDuration capability.
=> Added appWaitDuration capability

src/main/java/io/appium/java_client/pagefactory/AppiumElementLocator.java, src/main/java/io/appium/java_client/pagefactory/AppiumElementLocatorFactory.java, src/test/java/io/appium/java_client/pagefactory_tests/TimeOutResetTest.java
The additional test was provided
=> Addition to #467

src/main/java/io/appium/java_client/service/local/flags/AndroidServerFlag.java
Added ```--reboot``` android server flag.
https://github.com/appium/appium/pull/6822
=> Added reboot android server flag

src/main/java/io/appium/java_client/remote/AutomationName.java
The new AutomationName was added. ```ANDROID_UIAUTOMATOR2```. It is needed for the further development.
@TikhomirovSergey FYI :)
=> Added UIAutomator2 Automation Name

src/test/java/io/appium/java_client/ios/IOSAlertTest.java, src/test/java/io/appium/java_client/ios/IOSGesturesTest.java, src/test/java/io/appium/java_client/pagefactory_tests/AndroidPageObjectTest.java, src/test/java/io/appium/java_client/pagefactory_tests/IOSPageFactoryTest.java
Added CachedLookup tests for android and iOS pagefactory tests.
Logs for With-CachedLookup Test (https://gist.github.com/saikrishna321/a049586e43fc87d349f0cb27bee07758)
Logs for Without-CachedLookup Test (https://gist.github.com/saikrishna321/dae49547a721458495941fb89a9a80f1)
=> fixed-test and added CachedLookup tests

.travis.yml, README.md, src/test/java/io/appium/java_client/android/UIAutomator2Test.java
=> Added .travis.yml

src/test/java/io/appium/java_client/localserver/ServerBuilderTest.java
Refactored unit tests.
Cleanup unit tests.
=> Cleanup tests in ServerBuilderTest.

src/main/java/io/appium/java_client/remote/IOSMobileCapabilityType.java
Added XCUITest caps
- [ X] New feature (non-breaking change which adds functionality)
=> added xcuitest caps

docs/Installing-the-project.md
=> fix for Typo

README.md, build.gradle, src/main/java/io/appium/java_client/events/DefaultAspect.java, src/main/java/io/appium/java_client/events/DefaultListener.java, src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java, src/main/java/org/openqa/selenium/WebDriver.java, src/main/java/org/openqa/selenium/WebElement.java, src/test/java/io/appium/java_client/events/WebDriverEventListenerCompatibilityTest.java, src/test/java/io/appium/java_client/events/listeners/AppiumListener.java
=> Resetting master to Beta5

src/main/java/io/appium/java_client/AppiumFluentWait.java, src/main/java/io/appium/java_client/remote/AppiumProtocolHandShake.java, src/test/java/io/appium/java_client/appium/AppiumFluentWaitTest.java, src/test/java/io/appium/java_client/ios/XCUIAutomationTest.java
- the AppiumFluentWaitTest was improved
- minor codestyle issue fixes
=> The addition to the #612

src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java, src/main/java/io/appium/java_client/remote/IOSMobileCapabilityType.java, src/main/java/io/appium/java_client/remote/MobileCapabilityType.java
=> Capabilities Updates

README.md, build.gradle, src/main/java/io/appium/java_client/pagefactory/AppiumElementLocatorFactory.java, src/main/java/io/appium/java_client/pagefactory/DefaultElementByBuilder.java, src/main/java/io/appium/java_client/pagefactory/WidgetByBuilder.java
=> 	Dependendencies were updated.

docs/The-starting-of-an-app-using-Appium-node-server-started-programmatically.md
Fix typo in docs, `docs/The-starting-of-an-app-using-Appium-node-server-started-programmatically.md`.
No details.
=> fix Typo in docs

src/main/java/io/appium/java_client/internal/ElementMap.java, src/main/java/io/appium/java_client/pagefactory/WidgetByBuilder.java
_orElse_ method invokes the argument in any case, even if the result is not used, and _orElseGet_ does this only if necessary.
=> Avoid making unnecessary function calls

build.gradle
Use single quotes for strings w/o interpolated expressions in build.gradle.
It's recommended to use single quotes for simple strings (without interpolated expressions): http://groovy-lang.org/syntax.html#all-strings
=> Use single quotes for strings w/o interpolated expressions

build.gradle
Selenium modules changes:
- PhantomJS drop: https://github.com/SeleniumHQ/selenium/commit/8afc2428ce676bdb85c6906c749a7cf70339e51f
- Replace cglib with bytebuddy: https://github.com/SeleniumHQ/selenium/commit/07b7b540a7f4e6ebb7c3c4715e6fd791dd8aa082
=> Remove redundant Selenium modules exclusions

src/main/java/io/appium/java_client/MobileCommand.java, src/test/java/io/appium/java_client/android/AndroidDriverTest.java
The addition to the #812. test syncing.
=> push file. The addition to the #812

docs/environment.md
I see many people have problems with it. Perhaps, this document will help them.
=> Add environment troubleshooting doc

src/test/java/io/appium/java_client/ios/ImagesComparisonTest.java
`BaseIOSTest` is not the correct one
=> Tune test class ancestor

build.gradle
Current master branch cuases compilation error due to the missing module :(
=> Add the missing module into gradle config

src/main/java/io/appium/java_client/InteractsWithFiles.java, src/main/java/io/appium/java_client/android/PushesFiles.java, src/main/java/io/appium/java_client/ios/PushesFiles.java
The set of server features has been slightly updated since these methods exist in java client.
=> Update the documentation on push/pull file helpers

src/main/java/io/appium/java_client/remote/AutomationName.java
Adding ESPRESSO automation name
=> Adding ESPRESSO automation name

src/main/java/io/appium/java_client/android/AndroidDriver.java, src/main/java/io/appium/java_client/ios/IOSDriver.java
Addresses https://github.com/appium/java-client/issues/933
=> fix class cast exception on getting battery info

.travis.yml
Enable caching on Travis (https://docs.travis-ci.com/user/languages/java/#Caching)
=> Enable caching on Travis

build.gradle
Remove duplicate test dependency declaration
=> Remove duplicate test dependency declaration

archive/docs/Page-objects.md
Reverts appium/java-client#977
=> Revert "Update Page-objects.md"

src/main/java/io/appium/java_client/android/AndroidStartScreenRecordingOptions.java
Based on 
https://github.com/appium/appium-android-driver/pull/399
=> Update the documentation on timeLimit argument

docs/Installing-the-project.md
=> Link broken to getting started

build.gradle
Upgrade to JaCoCo 0.8.1 (required to build successfully on JDK 9+)
=> Upgrade to JaCoCo 0.8.1

build.gradle
=> Upgrade to JaCoCo 0.8.2

build.gradle
=> Upgrade to Checkstyle 8.12

src/main/java/io/appium/java_client/pagefactory/Widget.java, src/main/java/io/appium/java_client/pagefactory/utils/WebDriverUnpackUtility.java
Replace `org.openqa.selenium.internal.WrapsElement` with `org.openqa.selenium.WrapsElement`
=> Replace `org.openqa.selenium.internal.WrapsElement` with `org.openqa.selenium.WrapsElement`

src/main/java/io/appium/java_client/imagecomparison/OccurrenceMatchingOptions.java
Add the previously forgotten argument
Addresses https://github.com/appium/appium/issues/11705
=> Add threshold argument to OccurrenceMatchingOptions

gradle.properties
=> Update to selenium 3.141.59

src/main/java/io/appium/java_client/Setting.java, src/main/java/io/appium/java_client/android/HasAndroidSettings.java
Based on https://github.com/appium/appium-uiautomator2-server/pull/237
=> Add a setting for tag names normalization

build.gradle, gradle/wrapper/gradle-wrapper.properties
* Upgrade to Gradle 5.0,
* Remove Maven Publish Plugin as we are not using it currently.
@mykola-mokhnach ping
=> Upgrade to Gradle 5.0

build.gradle
=> Upgrade to Checkstyle 8.17

build.gradle, src/test/java/io/appium/java_client/android/AndroidScreenRecordTest.java, src/test/java/io/appium/java_client/events/ExtendedEventListenerTest.java, src/test/java/io/appium/java_client/events/WebDriverEventListenerCompatibilityTest.java, src/test/java/io/appium/java_client/ios/IOSScreenRecordTest.java, src/test/java/io/appium/java_client/touch/TouchOptionsTests.java
=> Migrate to Hamcrest 2.1

src/main/java/io/appium/java_client/events/DefaultAspect.java
fix #1147 
delete nonexistent class `io.appium.java_client.FindsByIosUIAutomation` (deleted at 67112e6) from `DefaultAspect`
=> delete nonexistent class from DefaultAspect

.travis.yml, azure-pipelines.yml, google-style.xml, src/test/java/io/appium/java_client/android/SettingTest.java, src/test/java/io/appium/java_client/appium/element/generation/BaseElementGenerationTest.java, src/test/java/io/appium/java_client/appium/element/generation/android/AndroidElementGeneratingTest.java, src/test/java/io/appium/java_client/appium/element/generation/ios/IOSElementGenerationTest.java, src/test/java/io/appium/java_client/ios/BaseIOSTest.java, src/test/java/io/appium/java_client/ios/BaseSafariTest.java, src/test/java/io/appium/java_client/ios/IOSElementTest.java, src/test/java/io/appium/java_client/ios/SettingTest.java, src/test/java/io/appium/java_client/service/local/StartingAppLocallyTest.java
Update Azure pipeline to make it green and remove functional tests from Travis since they are anyway not stable
=> Update CI scripts

gradle.properties, src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java, src/main/java/io/appium/java_client/remote/AppiumW3CHttpCommandCodec.java
- Upgrade to Selenium 4.0.0-alpha-1
=> Upgrade to Selenium 4.0.0-alpha-1

src/test/java/io/appium/java_client/android/AndroidDriverTest.java
I fixed some broken android tests. They were caused by wrong package name.
=> fix some broken android tests

.travis.yml, azure-pipelines.yml, jitpack.yml
Fix CI: change task name: signArchives -> signMavenJavaPublication
=> Fix CI: change task name: signArchives -> signMavenJavaPublication

build.gradle, src/main/java/io/appium/java_client/pagefactory/AndroidFindByAllSet.java, src/main/java/io/appium/java_client/pagefactory/AndroidFindByChainSet.java, src/main/java/io/appium/java_client/pagefactory/AndroidFindBySet.java, src/main/java/io/appium/java_client/pagefactory/WindowsFindByAllSet.java, src/main/java/io/appium/java_client/pagefactory/WindowsFindByChainSet.java, src/main/java/io/appium/java_client/pagefactory/WindowsFindBySet.java, src/main/java/io/appium/java_client/pagefactory/iOSXCUITFindByAllSet.java, src/main/java/io/appium/java_client/pagefactory/iOSXCUITFindByChainSet.java, src/main/java/io/appium/java_client/pagefactory/iOSXCUITFindBySet.java
- Upgrade to Checkstyle 8.22
- Fix all checkstyle violations
- Enable checkstyle checks in CI
=> Checkstyle updates

jitpack.yml
=> Fix builds in jitpack.io

docs/The-starting-of-an-app-using-Appium-node-server-started-programmatically.md
=> Renamed maim.js to main.js

.github/workflows/gradle-wrapper-validation.yml
See: https://github.com/gradle/wrapper-validation-action
=> Add GitHub Action validating Gradle wrapper

build.gradle, google-style.xml
=> chore: Upgrade to Checkstyle 8.29

src/main/java/io/appium/java_client/remote/MobileCapabilityType.java
Added OTHER_APPS and PRINT_PAGE_SOURCE_ON_FIND_FAILURE Mobile Capability Types.
- [x ] New feature (non-breaking change which adds functionality)
Adding values from [Capabilities Docs](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md) that I noticed weren't in java-client.
(ref: https://github.com/appium/java-client/pull/1319#discussion_r399763412)
=> add mobile capability settings

build.gradle
=> upgrade dependencies

.dependabot/config.yml
Adds the bot, which keeps gradle components up to date
=> chore: Add dependabot

build.gradle
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation
Fixes #1415
Fix the configuration of the dependency
=> Fix the configuration of `selenium-java` dependency

src/main/java/io/appium/java_client/Setting.java
Add 'boundElementsByIndex' setting, which was added in Appium 1.18.0, to Settings.java.
=> feat: Add 'boundElementsByIndex' to Settings

build.gradle
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
=> build: remove JCenter repository

src/main/java/io/appium/java_client/pagefactory/DefaultElementByBuilder.java, src/main/java/io/appium/java_client/pagefactory/bys/builder/AppiumByBuilder.java
For now, tvOS case does not have iOS annotations such as `iOSXCUITFindBy`
=> feat: add iOS related find by annotations for tvOS

.github/workflows/gradle-wrapper-validation.yml, .github/workflows/gradle.yml
Improve CI by eliminating duplicate builds.
It will help to avoid such cases:
=> chore: Prevent duplicate builds for PRs from base repo branches

.github/workflows/gradle.yml
Enable dependencies caching in CI
=> build: enable dependencies caching

build.gradle
We are grateful for @valfirst's contribution to the project and I would be happy to add him to the official list of project devs.
=> chore: Add Valery Yatsynovich to the list of project developers

.github/workflows/gradle.yml
Add all LTS JDK to CI build matrix
Build on LTS JDKs to make sure the code works as expected on different JDK versions.
=> build: check build on JDK 8, 11, 17

src/main/java/io/appium/java_client/remote/options/SupportsOrientationOption.java
Fixes https://github.com/appium/java-client/issues/1685
=> fix: Pass orientation name capability in uppercase

README.md
Polish release notes for v8.1.0
=> docs: Polish release notes for v8.1.0

gradle.properties, src/main/java/io/appium/java_client/AppiumDriver.java
Address https://github.com/appium/java-client/issues/1701
=> fix: Perform safe typecast while getting the platform name

src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java, src/main/java/io/appium/java_client/service/local/ListOutputStream.java
=> AppiumDriverLocalService can handle outputStreams

src/test/java/io/appium/java_client/internal/ConfigTest.java, src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/combined/CombinedAppTest.java, src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/combined/CombinedWidgetTest.java, src/test/java/io/appium/java_client/service/local/ServerBuilderTest.java, src/test/java/io/appium/java_client/service/local/StartingAppLocallyAndroidTest.java, src/test/java/io/appium/java_client/service/local/StartingAppLocallyIosTest.java, src/test/java/io/appium/java_client/service/local/ThreadSafetyTest.java
[JUnit5 test classes and methods should have default package visibility](https://rules.sonarsource.com/java/RSPEC-5786)
=> test: updated JUnit5 test classes and methods to have default package visibility

.github/workflows/pr-title.yml
=> ci: Verify if the PR title complies with conventional commits spec

.github/workflows/publish.yml, build.gradle
Publish artifacts to maven central on release
=> ci: automated artefact publish to maven central

.github/workflows/gradle.yml
Skip GitHub Actions build on changes in documentation.
=> ci: Skip GH Actions build on changes in docs

src/test/java/io/appium/java_client/ios/IOSDriverTest.java
Fix the name of the parameter according to the changes in drivers.
Changes affecting the behavior of the test:
- https://github.com/appium/appium-xcuitest-driver/pull/1487
- https://github.com/appium/appium/pull/18037
=> test: Fix test broken by updates in `appium-xcuitest-driver`

.github/workflows/gradle.yml, appium-style.xml, azure-pipelines.yml, build.gradle, jitpack.yml, src/main/java/io/appium/java_client/MobileBy.java, src/main/java/io/appium/java_client/MobileCommand.java, src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java, src/main/java/io/appium/java_client/internal/CapabilityHelpers.java, src/main/java/io/appium/java_client/pagefactory/HowToUseLocators.java, src/main/java/io/appium/java_client/pagefactory/bys/builder/ByAll.java
Migrate to Checkstyle 10.6.0. It requires JDK 11, thus Gradle Checkstyle tasks are disabled when running on JDK with version less than 11 .
=> build: Migrate to Checkstyle 10

README.md
Replace Travis CI badge with GH Actions CI badge.
=> docs: Fix build badge to point GH Actions CI

.github/CODEOWNERS
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners:
> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own.
=> chore: Configure `CODEOWNERS` to automate review requests

.github/workflows/gradle.yml
Enable execution of unit tests in CI.
=> ci: Enable execution of unit tests in CI

build.gradle
Add Simple SLF4J binding to unit tests runtime: https://www.slf4j.org/manual.html#swapping .
This change fixes the following error:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
```
=> test: Add Simple SLF4J binding to unit tests runtime

azure-pipelines.yml, build.gradle
Merge misc tests suite into unit tests suite: no reason to keep separate suites for tests of the same level.
=> build: Merge misc tests suite into unit tests suite

build.gradle, jitpack.yml
Root cause is the changed Gradle behaviour: https://github.com/gradle/gradle/issues/24456
Restore Jitpack builds.
=> fix: Restore Jitpack builds

src/main/java/io/appium/java_client/remote/options/SupportsAutoWebViewOption.java
Addresses https://github.com/appium/java-client/issues/1916
=> fix: Update autoWebview capability name

src/test/java/io/appium/java_client/service/local/ServerBuilderTest.java
`--base-path` arg must start with `/`.
=> test: Fix Android test: `--base-path` arg must start with `/`

.github/workflows/gradle.yml
-  [x] No changes in production code.
=> tests: Use server releases from the main branch for testing

build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew
Bump Gradle from `8.3` to `8.4`
=> chore: Bump Gradle from `8.3` to `8.4`

CHANGELOG.md, gradle.properties
Release 8.6.0 and update release notes
=> release: version 8.6.0 and update release notes

.github/workflows/gradle.yml
- Remove Java 15 from build matrix
- Run Android tests on Java 17 (macOS)
- Add build on Java 21 (ubuntu)
=> ci: Use LTS Java in CI

build.gradle
- Remove unused declaration
- Optimize Gradle tasks configuration
=> chore: Optimize and clean up Gradle build script

README.md
Add recent versions of Selenium client to compatibility matrix.
=> docs: Add recent versions of Selenium client to compatibility matrix

CHANGELOG.md, gradle.properties
=> release: v9.1.0 and update release notes

src/main/java/io/appium/java_client/remote/SupportsLocation.java, src/test/java/io/appium/java_client/android/AndroidDriverTest.java, src/test/java/io/appium/java_client/ios/IOSDriverTest.java
Fixes #2108
Add missing invocation of `build()` method on `Map.Builder` object.
=> fix: Set correct geolocation coordinates of the current device

README.md
Add Appium Java client `9.1.0` and Selenium client `4.17.0` to Compatibility Matrix
=> docs: add Appium Java client `9.1.0` to Compatibility Matrix

CHANGELOG.md, README.md, gradle.properties
=> release: v9.2.0

build.gradle, src/test/java/io/appium/java_client/TestUtils.java, src/test/java/io/appium/java_client/pagefactory_tests/DesktopBrowserCompatibilityTest.java, src/test/java/io/appium/java_client/pagefactory_tests/TimeoutTest.java
=> build: Restore execution of lost tests

README.md, gradle.properties, src/main/java/io/appium/java_client/remote/AppiumProtocolHandshake.java
The PR address internal API changes in Selenium `4.19.0`: https://github.com/SeleniumHQ/selenium/pull/13308. 
=> chore: Bump minimum Selenium version to `4.19.0`

build.gradle
Bump Checkstyle from `10.12.1` to `10.14.2`
=> build: Bump Checkstyle from `10.12.1` to `10.14.2`

CHANGELOG.md, README.md, gradle.properties
=> release: v9.2.1

src/test/java/io/appium/java_client/android/nativekey/KeyEventTest.java
Add unit tests for Android `KeyEvent` to cover regression issue
=> test: Add unit tests for Android `KeyEvent`

src/main/java/io/appium/java_client/internal/filters/AppiumUserAgentFilter.java
=> refactor: Replace Guava `HttpHeaders` with Selenium `HttpHeader`

src/main/java/io/appium/java_client/proxy/Helpers.java
Based on the [proposal](https://github.com/appium/java-client/issues/2118#issuecomment-2099899356) by @AndrasFekete80
=> fix: Use current class loader for the ByteBuddy wrapper

build.gradle
Bump JaCoCo from `0.8.11` to `0.8.12`
https://github.com/jacoco/jacoco/releases/tag/v0.8.12
=> build(deps): Bump JaCoCo from `0.8.11` to `0.8.12`

build.gradle
Bump Checkstyle from `10.14.2` to `10.17.0`
https://checkstyle.sourceforge.io/releasenotes.html
=> build(deps): Bump Checkstyle from `10.14.2` to `10.17.0`

src/e2eAndroidTest/java/io/appium/java_client/android/AndroidBiDiTest.java, src/e2eAndroidTest/java/io/appium/java_client/android/BaseAndroidTest.java
Similar to https://github.com/appium/java-client/pull/2254
=> test: Add Android BiDi events test

build.gradle
Use new coordinates of Gradle Shadow plugin.
The maintenance of the plugin was transferred to the GradleUp organization to ensure future development, see https://github.com/GradleUp/shadow/issues/908.
=> build(deps): Use new coordinates of Gradle Shadow plugin

gradle.properties
Selenium introduced breaking changes, it's required to bump Selenium client version, see more at #2298
=> chore: Bump minimum Selenium version to `4.34.0`
