src/main/java/io/appium/java_client/TouchAction.java

Add versions of the three `longPress` methods that allow the user to set the duration of the press, in `ms`.
Resolves #165.

Add longPress methods with duration

---

pom.xml

Now I develop a Java test tool which depends on the appium java-client library.
My test tool supports both JUnit3 and JUnit4, and I don't want the appium java-client to include junit4 dependency since this dependency may cause conflict.
I think appium java-client requires junit4 dependency only for test scope.

junit dependency is not required for compile scope

---

README.md

Hi,
Just a minor documentation fix in case we need to exclude the selenium version on which the java-client depends on.
Cheers

Documentation issue fix

---

src/main/java/io/appium/java_client/pagefactory/ElementInterceptor.java
src/main/java/io/appium/java_client/pagefactory/ElementListInterceptor.java

page objects do tons of findElement(s) calls to appium server because they also forward finalize method invocations.

make sure that finalize calls on annotated fields in page objects don't send findElement calls

---

README.md
pom.xml
src/main/java/io/appium/java_client/pagefactory/AppiumAnnotations.java
src/main/java/io/appium/java_client/pagefactory/WebDriverUnpackUtility.java

Changes:
- update dependencies to Selenium 2.46
-I have found a problem recently. Page object fields couldn't be populated because a customized implementation of the SearhContext was used. So now it is possible to use classes like that as well as
WebDriver and WebElement. But user's SearchContext implementations have to implement WrapsElement or WrapsDriver too.

#201 fix update to Selenium 2.46 + Some improvements.

---

src/main/java/io/appium/java_client/pagefactory/AppiumAnnotations.java
src/main/java/io/appium/java_client/pagefactory/AppiumElementLocator.java
src/main/java/io/appium/java_client/pagefactory/ContentMappedBy.java
src/main/java/io/appium/java_client/remote/AutomationName.java
src/test/java/io/appium/java_client/pagefactory_tests/AndroidPageObjectTest.java
src/test/java/io/appium/java_client/pagefactory_tests/SelendroidModeTest.java
src/test/java/io/appium/java_client/pagefactory_tests/iOSPageObjectTest.java

Change list:
- fixed #184 and #211. Now the choosing is by-strategy is depending on only driver class. There was outdated code. Now it is updated. Summary:
So when here is __AnroidDriver__ and current context is native app then will be choosen By-strategy defined via __AndroidFindBy/AndroidFindBys/AndroidFindAll__ annotations.  When here is __IOSDriver__ and current context is native app then will be choosen By-strategy defined via __iOSFindBy/iOSFindBys/iOSFindAll__. annotations.
By-strategy that is built using defaul __FindBy/FindBys/FindAll__ will be used for browser/webview content or when there is no specific annotations for Android/iOS native apps.
There is one specific remark. If somebody desires to use their own Webdriver implementation then it has to implement HasCapabilities.
- …

Fix #184 Fix #211

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/DefaultGenericMobileDriver.java
src/main/java/io/appium/java_client/DefaultGenericMobileElement.java
src/main/java/io/appium/java_client/DeviceActionShortcuts.java
src/main/java/io/appium/java_client/HasAppStrings.java
src/main/java/io/appium/java_client/IllegalCoordinatesException.java
src/main/java/io/appium/java_client/InteractsWithApps.java
src/main/java/io/appium/java_client/InteractsWithFiles.java
src/main/java/io/appium/java_client/MobileDriver.java
src/main/java/io/appium/java_client/MobileElement.java
src/main/java/io/appium/java_client/ScrollsTo.java
src/main/java/io/appium/java_client/SwipeElementDirection.java
src/main/java/io/appium/java_client/TouchShortcuts.java
src/main/java/io/appium/java_client/TouchableElement.java
src/main/java/io/appium/java_client/android/AndroidDeviceActionShortcuts.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidElement.java
src/main/java/io/appium/java_client/android/HasNetworkConnection.java
src/main/java/io/appium/java_client/android/PushesFiles.java
src/main/java/io/appium/java_client/android/StartsActivity.java
src/main/java/io/appium/java_client/internal/JsonToMobileElementConverter.java
src/main/java/io/appium/java_client/ios/GetsNamedTextField.java
src/main/java/io/appium/java_client/ios/IOSDeviceActionShortcuts.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/ios/IOSElement.java

There is no serious changes but:
- source code format issues fix
- the unnecessary "public" modifier was removed from interfaces

Source code format issues fix

---

README.md
src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/HasAppStrings.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java
src/test/java/io/appium/java_client/ios/IOSDriverTest.java

With this change getAppStrings returns a Map<String, String>, making it easier to be used:
```
Map<String, String> strings = driver.getAppStrings();
String string_value = strings.get('string_id');
```

getAppStrings method returns a map instead of an string

---

src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java
src/test/java/io/appium/java_client/localserver/ServerBuilderTest.java
src/test/java/io/appium/java_client/localserver/ThreadSafetyTest.java

#283 fix Changes:
- Work with _java.util.concurrent.locks.ReentrantLock_ was incorect. It was causing deadlocks/hangings in multithreading. Now it is worked out and uses "fair" synchronization.
- Improvement of the service stopping.
- New tests were provided.

#283 fix: Improvement of AppiumDriverLocalService for the multithreading.

---

google-style.xml
pom.xml

Checkstyle validation to ensure google java code style is followed or not
##Details
Continuation of https://github.com/appium/java-client/pull/346
@TikhomirovSergey @Jonahss @bootstraponline Please take a look at this PR :)

Google Java Style validation

---

docs/Installing-xcuitest-driver.md
pom.xml
src/main/java/io/appium/java_client/FindsByIosNsPredicate.java
src/main/java/io/appium/java_client/MobileBy.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/ios/IOSElement.java
src/test/java/io/appium/java_client/ios/XCUIDriverTest.java

addition to the PR #352
- [x ] New feature (non-breaking change which adds functionality)
Codestyle issues fix

addition to the PR #352

---

pom.xml
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/Strategies.java
src/main/java/io/appium/java_client/pagefactory/iOSFindBy.java

#379 fix #371 fix
#379 fix:
- the nsPredicate parameter was added to the iOSFindBy annotation
#371 fix
-  the commandRepository field is public now. The modification of  the MobileCommand
Also:
- _net.lingala.zip4j_ _zip4j_ was included to only test-scope dependencies
- _commons-io_ was updated to the v2.5

#379 fix #371 fix

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/ios/IOSDriver.java

Changes:
- constructors like  AppiumDriver(executor, capabilities) were added to AndroidDriver and IOSDriver
- the MobileCommand was modified.  Modifiers of getC(String url) postC(String url) were changed to public.
This change makes possible to use java_client with solutions of other vendors that require commands which are not supported by default appium.

the constructor AppiumDriver(executor, capabilities) became public

---

README.md
src/main/java/io/appium/java_client/ios/GetsNamedTextField.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/test/java/io/appium/java_client/ios/IOSGesturesTest.java

The GetsNamedTextField interface has become deprecated
I think that the using of hardcoded locators is the bad practice. Also I think that user can handle these actions the better way.

The GetsNamedTextField interface has become deprecated

---

pom.xml
src/main/java/io/appium/java_client/pagefactory/OverrideWidgetReader.java
src/main/java/io/appium/java_client/pagefactory/WidgetInterceptor.java
src/test/java/io/appium/java_client/pagefactory_tests/widgets/PartiallyOverrideNegativeWidgetTest.java
src/test/java/io/appium/java_client/pagefactory_tests/widgets/PartiallyOverrideRottenTomatoes.java
src/test/java/io/appium/java_client/pagefactory_tests/widgets/PartiallyOverrideWidgetTest.java

#392 fix & #418 fix
- Now functionality should be like it is described by the wiki page. There are the positive and the negative tests which demonstrates it.
- the possible dependency conflict was eliminated.

#392 fix & #418 fix

---

src/main/java/io/appium/java_client/TouchAction.java
src/test/java/io/appium/java_client/pagefactory_tests/widgets/ios/simple/IOSMovie.java

* io.appium.java_client.TouchAction
* io.appium.java_client.pagefactory_tests.widgets.ios.simple.IOSMovie
In java_client code, `WebElement` parameter is casted to `RemoteWebElement`. 
It makes hard to create proxy object for `WebElement` (like Selenide and probably some other frameworks do). 
Actually only method `getId()` is used. This method is declared in interface `HasIdentity`. 
This pull request changes few places where `WebElement` is casted to `RemoteWebElement` so that it's not casted to `HasIdentity` instead of `RemoteWebElement`.
Old code:
```java
new ActionParameter("press", (RemoteWebElement) el);
```
new code:
```java
new ActionParameter("press", (HasIdentity) el);
```

Use weaker interface HasIdentity instead of class RemoteWebElement

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java

The complete #215 fix and addition to #403:
- The fix of the bug which has not been caught.
```
"status": 0,
"value": {
"platform": "LINUX",
"webStorageEnabled": false,
"takesScreenshot": true,
"javascriptEnabled": true,
"databaseEnabled": false,
"networkConnectionEnabled": true,
"locationContextEnabled": false,
"warnings": {
},
"desired": {
"app": "\/Users\/saikrisv\/git\/java-client\/java-client\/src\/test\/java\/io\/appium\/java_client\/IntentExample.apk",
"platformName": "Android",
"deviceName": "Android Emulator"
},
"app": "\/Users\/saikrisv\/git\/java-client\/java-client\/src\/test\/java\/io\/appium\/java_client\/IntentExample.apk",
"platformName": "Android",
"deviceName": "192.168.65.101:5555",
"deviceUDID": "192.168.65.101:5555",
"platformVersion": "5.0",
"appPackage": …
```

The complete #215 fix and addition to #403

---

src/main/java/io/appium/java_client/MobileElement.java
src/main/java/io/appium/java_client/ios/IOSElement.java
src/test/java/io/appium/java_client/android/AndroidElementTest.java

- The `setValue` method was moved to `MobileElement` from the `IOSElement`. It works agains 
text input elements on Android
- The `setValueTest` was added to `AndroidElementTest`.
As soon as the `/wd/hub/session/:sessionId?/element/:elementId?/value` works against Android now then it makes sense to return it back to the `MobileElement`.
Also read #427

The setValue method was moved to MobileElement.

---

pom.xml
src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/CommandExecutionHelper.java
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidElement.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/ios/IOSMobileCommandHelper.java

- update to Selenium 2.53.1
- the new class `CommandExecutionHelper`
- the new class `AndroidMobileCommandHelper`
- the new class `IOSMobileCommandHelper`
- `MobileCommand.commandRepository` is mutable now. Additional commands could be defined via
`MobileCommand.commandRepository.put(String, CommandInfo)` there.
- source code reafactoring
There are projects which based on Appium (modifications, additional customized automation layers and so on). In order to make client convenient these chandes were made:
- the ability to define additional commands directly was provided. 
`MobileCommand.commandRepository.put(String, CommandInfo)`
- access to mobile OS-specific commands and execution was made easier
- was added the ability to implement specific exctentions of the accessing to additional …

Convenient access to commands

---

src/main/java/io/appium/java_client/remote/YouiEngineCapabilityType.java
src/main/java/io/appium/java_client/youiengine/YouiEngineDriver.java
src/main/java/io/appium/java_client/youiengine/YouiEngineElement.java
src/main/java/io/appium/java_client/youiengine/internal/JsonToYouiEngineElementConverter.java

Added YouiEngineDriver.java and supporting files and classes.
Overloaded swipe method with a call to internal TouchAction method.
- [x ] New feature (non-breaking change which adds functionality)
Subclassed Appium Driver.
Swipe is a virtual method in the AppiumDriver which we subclass so we need to implement it. Originally we would call the super implementation and pass through the parameters but You.i Engine doesn't yet support 'duration' so I added an actual implementation.

Updated YouiEngineDriver to use CommandExecutor

---

src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java

Update Android Mobile Capability in sync with Appium Server 
@TikhomirovSergey FYI please review

AndroidMobileCapablitiy Updates

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/test/java/io/appium/java_client/ios/IOSAlertTest.java

Alert Handling for iOS.Added below methods,
```
1)getAlertText
2)setAlertText(String value)
3)acceptAlert
4)dismissAlert
```
API is here: https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js#L403
API's were not implemented for Android Driver on server side.We can port it to android driver on client side post server implementation.
New W3C API's here: https://github.com/appium/appium-base-driver/blob/master/lib/mjsonwp/routes.js#L414 are not been adapted by Appium (Legacy drivers on server) yet.
@TikhomirovSergey please review

Alert API Implementation for iOS

---

src/main/java/io/appium/java_client/pagefactory/AppiumElementLocator.java
src/main/java/io/appium/java_client/pagefactory/AppiumElementLocatorFactory.java

fix element timeout changing page object timeout issue 
this bug fixes #467

fix element timeout changing page object timeout issue

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/CommandExecutionHelper.java
src/main/java/io/appium/java_client/DefaultGenericMobileDriver.java
src/main/java/io/appium/java_client/DefaultGenericMobileElement.java
src/main/java/io/appium/java_client/DeviceActionShortcuts.java
src/main/java/io/appium/java_client/ExecutesMethod.java
src/main/java/io/appium/java_client/FindsByAccessibilityId.java
src/main/java/io/appium/java_client/FindsByIosNSPredicate.java
src/main/java/io/appium/java_client/FindsByIosUIAutomation.java
src/main/java/io/appium/java_client/FindsByWindowsAutomation.java
src/main/java/io/appium/java_client/HasAppStrings.java
src/main/java/io/appium/java_client/InteractsWithApps.java
src/main/java/io/appium/java_client/InteractsWithFiles.java
src/main/java/io/appium/java_client/MobileDriver.java
src/main/java/io/appium/java_client/PerformsTouchActions.java
src/main/java/io/appium/java_client/TouchableElement.java
src/main/java/io/appium/java_client/android/AndroidDeviceActionShortcuts.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidElement.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/HasNetworkConnection.java
src/main/java/io/appium/java_client/android/LocksAndroidDevice.java
src/main/java/io/appium/java_client/android/PushesFiles.java
src/main/java/io/appium/java_client/android/StartsActivity.java
src/main/java/io/appium/java_client/ios/IOSDeviceActionShortcuts.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/ios/IOSElement.java
src/main/java/io/appium/java_client/ios/IOSMobileCommandHelper.java
src/main/java/io/appium/java_client/ios/LocksIOSDevice.java
src/test/java/io/appium/java_client/events/FewInstancesTest.java

Epic: #399 
- each one interface extends the `io.appium.java_client.ExecutesMethod`
- both `AppiumDriver` and `MobileElement` implement `io.appium.java_client.ExecutesMethod`
- Current API has default implementation
- `AppiumDriver`, `MobileElement` and subclasses just declare interfaces are implemented. 
We have few targets: 
- We are going to support Windows Mobile automation. Some interesting things were found. It supports some functions which were declared as Android-specific. As well it may support some functions which were declared as iOS-only as well. So we need for very flexible API which allows to implement it easily and without copy-paste.
- Some users need to use Android/iOS specific functions eventually. Now …

Migration to Java 8. API with default implementation.

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/AppiumSetting.java
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/ConfiguratorParameters.java
src/main/java/io/appium/java_client/android/HasSettings.java
src/main/java/io/appium/java_client/android/Setting.java
src/main/java/io/appium/java_client/android/settings/Setting.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java
src/test/java/io/appium/java_client/android/SettingTest.java

- `io.appium.java_client.AppiumSetting` became deprecated. It was moved to `io.appium.java_client.android.Setting`.
- the method `io.appium.java_client.AppiumDriver#getSettings()` was completely moved to `io.appium.java_client.android.AndroidDriver`.
- the new interface `io.appium.java_client.android.HasSettings` was added. It has default implementation. And this interface is implemented by AndroidDriver.
Methods:
- `void setSetting(Setting setting, Object value) `
- `JsonObject getSettings() `
- `void ignoreUnimportantViews(Boolean compress)`
- `void configuratorSetWaitForIdleTimeout(int timeout) `
- `void configuratorSetWaitForSelectorTimeout(int timeout) `
- `void configuratorSetScrollAcknowledgmentTimeout(int timeout) `
- `void configuratorSetKeyInjectionDelay(int delay)`
- `void …

Android setting engine

---

build.gradle
src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/events/DefaultListener.java
src/main/java/io/appium/java_client/events/api/general/ElementEventListener.java
src/test/java/io/appium/java_client/events/EmptyWebDriver.java
src/test/java/io/appium/java_client/events/listeners/AppiumListener.java
src/test/java/io/appium/java_client/events/listeners/ElementListener.java
src/test/java/io/appium/java_client/events/listeners/ElementListener2.java

- Updated Selenium to 3.0
- Added new dependency ```common-io``` for handling file utilities
- Added ```beforeChangeValueOf``` and ```afterChangeValueOf``` element event listener methods.
- Fixed styling issues in ```AppiumDriver```
- Rotation support is added with @rafael-chavez authorship Refer: #439 
@TikhomirovSergey @rafael-chavez FYI please review

Selenium 3 updates

---

src/test/java/io/appium/java_client/ios/XCUIAutomationTest.java

Added tests for DeviceRotation API
```DeviceRotation``` API works only for ```XCUITest``` Mode now. It will throw ```CommandNotFound``` exception for other modes. It has been raised on server for implementation. Ref. https://github.com/appium/appium/issues/7131
@TikhomirovSergey Please review :)

Added tests for DeviceRotation API

---

build.gradle

Removed dependency from `build.gradle` dependencies list:
`compile 'com.google.code.gson:gson:2.6.2'`
as there already is a later version (`2.7`) included in the dependencies list.
```
compile 'com.google.code.gson:gson:2.7'            <--------
compile 'org.apache.httpcomponents:httpclient:4.5.2'
compile 'com.google.guava:guava:19.0'
compile 'cglib:cglib:3.2.4'
compile 'commons-validator:commons-validator:1.5.1'
compile 'org.apache.commons:commons-lang3:3.4'
compile 'commons-io:commons-io:2.5'
compile 'com.google.code.gson:gson:2.6.2'         <--------
compile 'org.springframework:spring-context:4.3.2.RELEASE'
compile 'org.aspectj:aspectjweaver:1.8.9'
```
- [x ] Bugfix (non-breaking …

removed obselete gson-2.6.2 dependency.

---

README.md
build.gradle
src/main/java/io/appium/java_client/CommandExecutionHelper.java
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/ios/IOSDeviceActionShortcuts.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/ios/IOSMobileCommandHelper.java
src/main/java/io/appium/java_client/ios/PerformsTouchID.java
src/test/java/io/appium/java_client/ios/IOSGesturesTest.java
src/test/java/io/appium/java_client/ios/XCUIAutomationTest.java

Added touchId command
Touch ID is a feature in Apple products (see https://support.apple.com/en-ca/HT201371). This endpoint simulates the behaviour.

TouchID Implementation [iOS Sim Only]

---

src/test/java/io/appium/java_client/android/UIAutomator2Test.java

Added Rotation tests with UIAutomator2
@TikhomirovSergey @SrinivasanTarget review pls

added UIAutomator2 rotation test

---

src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java
src/test/java/io/appium/java_client/android/UIAutomator2Test.java
src/test/java/io/appium/java_client/localserver/ServerBuilderTest.java

The addition to #522
- the ability use ip and log file as server args was provided
- test update/fix

The addition to #522

---

src/main/java/io/appium/java_client/TouchAction.java
src/main/java/io/appium/java_client/ios/IOSTouchAction.java
src/test/java/io/appium/java_client/ios/XCUIAutomationTest.java

DoubleTap support to IOSTouchAction
@rafael-chavez Apologies for the long delay. It is back in your authorship.
@TikhomirovSergey  FYI

[XCUIT Mode] DoubleTap Support

---

src/test/java/io/appium/java_client/android/UIAutomator2Test.java

Added test to verify TOAST messages
Should work with appium-uiautomator2-driver [v0.0.9](https://github.com/appium/appium-uiautomator2-driver/releases/tag/v0.0.9)
Note:
Because of the google UiAutomaor2 limitation, it is not possible to perform any operation on TOAST element, performing any operations [ex: `getText()`] will throw `StaleObjectExecption`. i.e It is only possible to verify the TOAST message.
@SrinivasanTarget please review

Added test to verify TOAST messages

---

archive/docs/How-to-propose-a-PR.md
archive/docs/How-to-report-an-issue.md
archive/docs/Installing-the-project.md
archive/docs/Note-for-developers.md
archive/docs/Page-objects.md
archive/docs/The-event_firing.md
archive/docs/The-starting-of-an-Android-app.md
archive/docs/The-starting-of-an-app-using-Appium-node-server-started-programmatically.md
archive/docs/The-starting-of-an-iOS-app.md
archive/docs/Touch-actions.md
docs/Functions.md
docs/Installing-the-project.md
docs/Tech-stack.md
docs/The-starting-of-an-Android-app.md
docs/The-starting-of-an-app-using-Appium-node-server-started-programmatically.md
docs/The-starting-of-an-iOS-app.md
docs/Touch-actions.md

Documentation was synced to latest changes
I am going to improve WIKI after the merging.

Documentation was synced to latest changes

---

README.md
build.gradle
src/main/java/io/appium/java_client/PerformsActions.java
src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java
src/test/java/io/appium/java_client/localserver/ThreadSafetyTest.java
src/test/java/io/appium/java_client/pagefactory_tests/GenericTest.java
src/test/java/io/appium/java_client/pagefactory_tests/SelendroidModeTest.java

- dependencies update
- product version was changed
- README was re-written. 
- some codecy issues were fixed

Updated dependencies

---

src/main/java/io/appium/java_client/remote/IOSMobileCapabilityType.java

Added below XCUIT caps,
```
USE_NEW_WDA,
WDA_LAUNCH_TIMEOUT,
WDA_CONNECTION_TIMEOUT
```
Removed ```REAL_DEVICE_LOGGER``` in sync with server.

XCUIT Caps Updates

---

docs/Installing-the-project.md

I'm working on a project now using this library and noticed this small typo when trying to prepare my `pom.xml` file. This is a great project—thanks for all your work!

Fix a tiny XML typo (Installing-the-project.md)

---

build.gradle

To build fatJar, apply this PR patch and simply call `./gradlew shadowJar`
* Adding support for the new gradle plugins block
* Using the shadow plugin to create a fatJar for appium java client.
* Usage of plugins block makes buildscript terse
* Allowing building fatJars helps makes life easy for cmd line usage.

new gradle plugins block + fatJar

---

docs/The-starting-of-an-Android-app.md
src/main/java/io/appium/java_client/android/Activity.java
src/main/java/io/appium/java_client/android/StartsActivity.java
src/test/java/io/appium/java_client/android/AndroidAbilityToUseSupplierTest.java
src/test/java/io/appium/java_client/android/AndroidActivityTest.java
src/test/java/io/appium/java_client/android/AndroidContextTest.java
src/test/java/io/appium/java_client/android/AndroidElementTest.java
src/test/java/io/appium/java_client/android/AndroidFunctionTest.java
src/test/java/io/appium/java_client/android/AndroidSearchingTest.java
src/test/java/io/appium/java_client/android/AndroidTouchTest.java
src/test/java/io/appium/java_client/android/IntentTest.java
src/test/java/io/appium/java_client/android/UIAutomator2Test.java
src/test/java/io/appium/java_client/appium/AndroidTest.java
src/test/java/io/appium/java_client/pagefactory_tests/widgets/AndroidOverrideWidgetTest.java
src/test/java/io/appium/java_client/pagefactory_tests/widgets/android/AndroidWidgetTest.java
src/test/java/io/appium/java_client/pagefactory_tests/widgets/combined/AndroidCombinedWidgetTest.java

Simplified the StartsActivity by reducing the number of parameters through POJO class
Currently the number of `startActivity` methods are unnecessary which can be solved by one single method with single parameter. So introduced the simple POJO class which in future can be expanded with any number of parameters.
The sample usage of new implementation is as follows:
```java
Activity activity = new Activity();
activity.setAppPackage("com.foo");
activity.setAppActivity(".bar");
driver.startActivity(activity);
```

Simplified the StartsActivity by reducing the number of parameters through POJO class

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/HasSupportedPerformanceDataType.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java

add apis to read the resource usage information of the application as like cpu, memory, network traffic, and battery
The appium already has a way to gather the performance data by log.
but If the resulting data format is set to a log file, the user should conduct another parsing to show the data on the screen.
also I think user wants to decide the moment to read the data and associate the performance data and other information.
so I’d like to add apis to gather the performance data.
please refer below the commit code 
- https://github.com/appium/appium-base-driver/commit/0fd67e4efbed9c8a8352b18557b84b10649baabc
- https://github.com/appium/appium-android-driver/commit/1e6c644a9260ca22726 …

add apis to read the performance data

---

README.md
docs/The-starting-of-an-Android-app.md
src/main/java/io/appium/java_client/android/Activity.java
src/main/java/io/appium/java_client/android/HasSupportedPerformanceDataType.java
src/test/java/io/appium/java_client/android/AndroidActivityTest.java
src/test/java/io/appium/java_client/android/IntentTest.java

The chaining of the activity parameter setting.

Addition to the #579

---

src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java

When automation to be run with UIAutomator2 capability for android, often instrumentation crash.
To mitigate we need to provide "systemPort" capability as a part of desired capability. 
This minor change and just tokenise "systenPort" into AndroidMobileCapability.
As per @sravanmedarapu suggestion, In order to run Appium test with UIAutomator2 capability; it requires systemPort capability to be provided to keep parallel sessions alive. For further detail please find below link,
https://github.com/appium/appium/issues/7745#issuecomment-275417210
This changes is just tokenise "systemPort" capability into AndroidMobileCapability and its a very minor change to java-client.

Added System Port capability in AndroidMobileCapabilityType

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/test/java/io/appium/java_client/ios/XCUIAutomationTest.java

See details.
This change is based on https://github.com/appium/appium-xcuitest-driver/pull/381, which makes possible to minimize the application under test and then return to iOS springboard (emulates clicking Home button). The change is breaking since the format of input parameters has been changed for **background** API call (the old format is still supported, but shows deprecation warning).

Update runAppInBackground method implementation for XCUITest

---

src/main/java/io/appium/java_client/FindsByIosClassChain.java
src/main/java/io/appium/java_client/MobileBy.java
src/main/java/io/appium/java_client/MobileSelector.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/Strategies.java
src/main/java/io/appium/java_client/pagefactory/iOSXCUITFindBy.java
src/test/java/io/appium/java_client/pagefactory_tests/XCUITModeTest.java

Adds a new class chain locator type for iOS XCUITest-based driver
This PR is based on https://github.com/appium/appium-xcuitest-driver/pull/391
Class chain locator description and usage examples are present on https://github.com/facebook/WebDriverAgent/wiki/Queries

Add class chain locator type for iOS XCUITest-based driver

---

src/main/java/io/appium/java_client/AppiumFluentWait.java
src/test/java/io/appium/java_client/appium/AppiumFluentWaitTest.java

Created extended FluentWait class with possibility to allow custom polling strategy. This might be quite useful while working with mobile interfaces where the initial transition animation creates main delay before an element appears on the screen. Having custom polling strategy set allows one to increase this initial polling delay, so the interface has enough time to finish the transition faster without being unnecessarily interrupted by Appium agent calls.
I don't really like the implementation myself, since it is necessary to access private fields of the parent class via reflection API. Please let me know if you have better ideas on how to implement it.

Extend FluentWait, so one can set custom polling strategy

---

src/main/java/io/appium/java_client/InteractsWithApps.java
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/SwipeElementDirection.java
src/main/java/io/appium/java_client/TouchAction.java
src/main/java/io/appium/java_client/android/HasSettings.java
src/main/java/io/appium/java_client/ios/LocksIOSDevice.java
src/test/java/io/appium/java_client/android/AndroidAbilityToUseSupplierTest.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java
src/test/java/io/appium/java_client/android/AndroidTouchTest.java
src/test/java/io/appium/java_client/android/SettingTest.java
src/test/java/io/appium/java_client/ios/IOSDriverTest.java
src/test/java/io/appium/java_client/ios/IOSTouchTest.java
src/test/java/io/appium/java_client/pagefactory_tests/widgets/android/simple/AndroidMovie.java
src/test/java/io/appium/java_client/pagefactory_tests/widgets/ios/simple/IOSMovie.java

Replace timeout/duration arguments where possible with _java.time.Duration_ type, which has been introduced in Java 8.. This gives us better control over time conversion and helps to avoid time unit conversion issues in general.
All the existing methods, that have replacements, were marked as deprecated.

Use java.time.Duration to represent time deltas instead of elementary types

---

build.gradle
src/main/java/io/appium/java_client/ScreenshotState.java
src/test/java/io/appium/java_client/utils/ScreenshotStateTests.java

This feature has been asked by several users, so I've just nicely decorated the code we use in our own automation framework and added it to the client.
- [ x ] New feature (non-breaking change which adds functionality)
Screenshots comparison algorithm itself is based on standard opencv calls. That is why the library has been added to Gradle config as a dependency.

Add possibility to calculate screenshots overlap score + several helpers

---

archive/docs/How-to-propose-a-PR.md
archive/docs/How-to-report-an-issue.md
docs/Functions.md
docs/How-to-propose-a-PR.md
docs/How-to-report-an-issue.md
docs/Installing-the-project.md
docs/Tech-stack.md
docs/The-starting-of-an-Android-app.md
docs/The-starting-of-an-iOS-app.md
docs/Touch-actions.md

GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1

Fix broken headings in Markdown files

---

src/main/java/io/appium/java_client/pagefactory/AppiumElementLocatorFactory.java
src/main/java/io/appium/java_client/pagefactory/DefaultElementByBuilder.java
src/main/java/io/appium/java_client/pagefactory/WidgetByBuilder.java

[link to issue](https://github.com/appium/java-client/issues/628)

Made some pagefactory classes public

---

build.gradle
src/main/java/io/appium/java_client/youiengine/YouiEngineDriver.java
src/main/java/io/appium/java_client/youiengine/YouiEngineElement.java

- all the content of the `io.appium.java_client.youiengine` package was marked as `Deprecated`
- update of the `com.google.code.gson:gson` to v2.8.1
This package was added at #429. It was accepted due to previous implementation was not flexible and it did not allowed user to use their own commands/JSONWP protocol extensions. Now `AppiumDriver` is not abstract and it can be used across supported platfoms. 
Please take a look at the following sample: 
```java
...
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.Activity;
import io.appium.java_client.android.AndroidElement;
...
private static AppiumDriver<AndroidElement> driver;
private StartsActivity startsActivity;
...
DesiredCapabilities capabilities = new DesiredCapabilities();
...
driver = new …
```

Deprecated youiengine

---

src/main/java/io/appium/java_client/AppiumSetting.java
src/main/java/io/appium/java_client/HasSettings.java
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/Setting.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/HasAndroidSettings.java
src/main/java/io/appium/java_client/ios/HasIOSSettings.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/test/java/io/appium/java_client/android/SettingTest.java
src/test/java/io/appium/java_client/ios/BaseSafariTest.java
src/test/java/io/appium/java_client/ios/IOSNativeWebTapSettingTest.java

add a setting for iOS to toggle `nativeWebTap`
Server-side change: https://github.com/appium/appium-xcuitest-driver/pull/455

enable nativeWebTap setting for iOS

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/StartsActivity.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java

Appium 1.6.6 beta has a new endpoint for getting the currently running package during an Android test.
See appium/appium-base-driver@190a896
Re: appium/appium#8674

added get_current_package session

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/ios/IOSMobileCommandHelper.java
src/main/java/io/appium/java_client/ios/PerformsTouchID.java
src/test/java/io/appium/java_client/ios/AppXCUITTest.java
src/test/java/io/appium/java_client/ios/XCUIAutomationTest.java

Fix #607 
For ref https://github.com/appium/appium-xcuitest-driver/pull/402
@dpgraham @TikhomirovSergey please review

Add toggleTouchIdEnrollment function

---

src/main/java/io/appium/java_client/MultiTouchAction.java
src/main/java/io/appium/java_client/PerformsTouchActions.java
src/main/java/io/appium/java_client/TouchAction.java

Clear existing actions/parameters after _perform_ method of the corresponding actions chain is invoked
I find the current behaviour confusing, since it may cause issues like this one: https://github.com/appium/appium/issues/8734
The second possible solution might be to make a chain immutable after _perform_ is called, so it will reject all the further parameter/action adding operations after _perform_ method has been invoked once on a chain instance.

Clear existing actions/parameters after perform is invoked

---

src/main/java/io/appium/java_client/pagefactory/DefaultElementByBuilder.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/AppiumByBuilder.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/ByAll.java

PR issue fix.

---

src/main/java/io/appium/java_client/pagefactory/DefaultElementByBuilder.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/AppiumByBuilder.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/ByAll.java

ByAll was re-implemented. Now it return the fist founded element for single search.
This changes improve time of seaching single element for 'All Possible' strategy. Now it doesn't search all possible elements for single.
Selenium implementation was for single search: invoke `findElements` method and return the first element in list.

ByAll was re-implemented.

---

src/main/java/io/appium/java_client/ios/IOSMobileCommandHelper.java
src/main/java/io/appium/java_client/ios/PerformsTouchID.java
src/test/java/io/appium/java_client/ios/XCUIAutomationTest.java

Now it is possible to set the desired state for Touch ID Enrolment feature.
the PR is based on https://github.com/appium/appium-xcuitest-driver/pull/506

Update touch ID enroll method

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/ios/PushesFiles.java

The PR adds support of pushFile endpoint to IOSDriver. For now it is only possible to upload media file to Simulator.
Addresses https://github.com/appium/java-client/issues/720

Add pushFile support to IOSDriver

---

src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java

I see many people are struggling because of the fact that we set an empty environment by default while building Appium executor. This causes Appium drivers to fail unexpectedly since they cannot find executables that are supposed to available in PATH. This PR adds all the inherited process env variable to the builder by default.

Inherit the default process environment by default

---

src/main/java/io/appium/java_client/Setting.java

This sets waitForIdleTimeout via settings. 
removed prefix "set" from enum constant setWaitForIdleTimeout.
appium-uiautomator2-server and appium-android-bootstrap expects "waitForIdleTimeout" 
PR implementing waitForIdleTimeout in appium-uiautomator2-server
https://github.com/appium/appium-uiautomator2-server/pull/80

Removed 'set' prefix from waitForIdleTimeout setting

---

src/main/java/io/appium/java_client/DefaultGenericMobileDriver.java
src/main/java/io/appium/java_client/internal/ElementMap.java
src/main/java/io/appium/java_client/internal/JsonToMobileElementConverter.java
src/main/java/io/appium/java_client/pagefactory/AppiumElementLocator.java
src/main/java/io/appium/java_client/pagefactory/AppiumFieldDecorator.java
src/main/java/io/appium/java_client/pagefactory/WidgetListInterceptor.java
src/main/java/io/appium/java_client/pagefactory/bys/ContentMappedBy.java
src/main/java/io/appium/java_client/pagefactory/utils/WebDriverUnpackUtility.java

#764 FIX. This change was made according to the confersation #765

#764 alternative fix

---

build.gradle
src/main/java/io/appium/java_client/events/DefaultAspect.java
src/main/java/io/appium/java_client/events/DefaultListener.java
src/main/java/io/appium/java_client/events/api/general/AlertEventListener.java
src/test/java/io/appium/java_client/events/BaseListenerTest.java
src/test/java/io/appium/java_client/events/ListenableObjectTest.java

- Update to selenium 3.7.1
- Methods `beforeAuthentication` and afterAuthentication` became deprecared.
- @mykola-mokhnach was added to the list of developers.
I can't to update the project to selenium 3.8.x because of mentioned methods. It should be removed safely and users should be warned.

Update to selenium 3.7.1

---

src/main/java/io/appium/java_client/PressesKeyCode.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AuthenticatesByFinger.java
src/test/java/io/appium/java_client/android/FingerPrintTest.java

Additional changes of the #473
- AuthenticatesByFinger was added to `io.appium.java_client.android`
- Some improvements of the FingerPrintTest

 Additional changes of the #473

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/PressesKeyCode.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/test/java/io/appium/java_client/android/FingerPrintTest.java

added finger print function to android driver. defined the command url and helper method, and created an Action shortcut to use it.
it is a simple function to activate emulators fingerprint sensor. the command is like `driver.fingerPrint(x)` where x is the finger number (1 to 10). this command is created based on [add finger print to route](https://github.com/appium/appium-base-driver/pull/74#issuecomment-246322174)

add finger print command to android Driver

---

src/main/java/io/appium/java_client/TouchAction.java
src/main/java/io/appium/java_client/touch/offset/PointOption.java
src/test/java/io/appium/java_client/touch/TouchOptionsTests.java

`moveTo` fix is not deployed to Appium yet, so it's OK to allow clients to still use relative coordinates. I've also added a note about the problem into the docstring.

Less strict verification

---

build.gradle
src/main/java/io/appium/java_client/events/DefaultListener.java
src/main/java/io/appium/java_client/events/api/general/AlertEventListener.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/test/java/io/appium/java_client/events/StubAlert.java
src/test/java/io/appium/java_client/events/WebDriverEventListenerCompatibilityTest.java
src/test/java/io/appium/java_client/events/listeners/AlertListener.java
src/test/java/io/appium/java_client/events/listeners/AlertListener2.java

- Update to Selenium 3.8.1
- Removal of deprecated listener-methods from the AlertEventListener. These methods were
being invoked before/after authentication.

Update to Selenium 3.8.1

---

src/main/java/io/appium/java_client/pagefactory/iOSFindAll.java
src/main/java/io/appium/java_client/pagefactory/iOSFindBys.java
src/main/java/io/appium/java_client/pagefactory/iOSXCUITFindAll.java
src/main/java/io/appium/java_client/pagefactory/iOSXCUITFindBys.java

Compare 2 builds (source code is the same):
1. https://travis-ci.org/appium/java-client/builds/329196333:
```
[ant:checkstyle] [ERROR] /home/travis/build/appium/java-client/src/main/java/io/appium/java_client/pagefactory/iOSFindAll.java:29: Javadoc comment at column 14 has parse error. Details: no viable alternative at input 'i' while parsing REFERENCE [SingleLineJavadoc]
[ant:checkstyle] [ERROR] /home/travis/build/appium/java-client/src/main/java/io/appium/java_client/pagefactory/iOSFindBys.java:29: Javadoc comment at column 23 has parse error. Details: no viable alternative at input 'i' while parsing REFERENCE [SingleLineJavadoc]
[ant:checkstyle] [ERROR] /home/travis/build/appium/java-client/src/main/java/io/appium/java_client/pagefactory/iOSXCUITFindAll.java:29: Javadoc comment at …
```

Fix flaky checkstyle violations

---

build.gradle

The Java plugin defines two standard source sets, called `main` and `test`. There is no reason to duplicate their declaration. (https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_source_sets)

Use standard Java plugin source sets

---

src/main/java/io/appium/java_client/MobileCommand.java

Fixes the second argument type for `pushFile` endpoint. Appium expects it to be base64-encoded string, but we send array of bytes instead.
See https://github.com/appium/appium-xcuitest-driver/pull/605

Fix the second argument type for pushFile

---

src/main/java/io/appium/java_client/AppiumW3CHttpCommandCodec.java
src/main/java/io/appium/java_client/internal/JsonToMobileElementConverter.java
src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java
src/main/java/io/appium/java_client/remote/AppiumW3CHttpCommandCodec.java

Addition to the #817. JsonToMobileElementConverter: fixed

 Addition to the #817. JsonToMobileElementConverter: fixed

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/android/AndroidStopScreenRecordingOptions.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/ios/IOSStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/ios/IOSStopScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/BaseScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/BaseStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/BaseStopScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/CanRecordScreen.java
src/main/java/io/appium/java_client/screenrecording/ScreenRecordingUploadOptions.java
src/test/java/io/appium/java_client/android/AndroidScreenRecordTest.java
src/test/java/io/appium/java_client/ios/IOSScreenRecordTest.java

Add endpoints for screen recording API for iOS and Android
https://github.com/appium/appium-android-driver/pull/303
https://github.com/appium/appium-xcuitest-driver/pull/609

Add endpoints for screen recording API for iOS and Android

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/GsmCallActions.java
src/main/java/io/appium/java_client/android/GsmSignalStrength.java
src/main/java/io/appium/java_client/android/GsmVoiceState.java
src/main/java/io/appium/java_client/android/NetworkSpeed.java
src/main/java/io/appium/java_client/android/PowerACState.java
src/main/java/io/appium/java_client/android/SupportsSpecialEmulatorCommands.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java

Add handlers for gsm, network, power and sms command
https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L366-L375
@mykola-mokhnach ping

Add handlers for gsm, network, power and sms command

---

src/main/java/io/appium/java_client/remote/AppiumW3CHttpCommandCodec.java

Add missing handler for `isDisplayed` endpoint , which is missing in W3C mode. In the original codec it's replaced with executeScript alias.

Add a handler for isDispalyed endpoint in W3C mode

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/SupportsNetworkStateManagement.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java
src/test/java/io/appium/java_client/android/BaseAndroidTest.java

#835 added handlers for toggle_wifi,data and airplane mode

---

google-style.xml
src/main/java/io/appium/java_client/InteractsWithApps.java
src/main/java/io/appium/java_client/LocksDevice.java
src/main/java/io/appium/java_client/android/AndroidStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/android/SupportsNetworkStateManagement.java
src/main/java/io/appium/java_client/android/appmanagement/AndroidInstallApplicationOptions.java
src/main/java/io/appium/java_client/android/appmanagement/AndroidRemoveApplicationOptions.java
src/main/java/io/appium/java_client/android/appmanagement/AndroidTerminateApplicationOptions.java
src/main/java/io/appium/java_client/ios/IOSStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/remote/AppiumW3CHttpCommandCodec.java
src/main/java/io/appium/java_client/screenrecording/BaseScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/BaseStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/CanRecordScreen.java
src/main/java/io/appium/java_client/screenrecording/ScreenRecordingUploadOptions.java
src/test/java/io/appium/java_client/android/AndroidScreenRecordTest.java
src/test/java/io/appium/java_client/ios/IOSScreenRecordTest.java

- Fix `CustomImportOrder` checkstyle violations
- Change severity of `CustomImportOrder` checkstyle rule from `warning` to default (`error`)
- Fix `SummaryJavadoc` checkstyle violations
- Change severity of `SummaryJavadoc` checkstyle rule from `warning` to default (`error`)
- Fix `JavadocTagContinuationIndentation` checkstyle violations
- Change severity of `JavadocTagContinuationIndentation` checkstyle rule from `warning` to default (`error`)

Fix checkstyle violations

---

src/main/java/io/appium/java_client/android/AndroidStartScreenRecordingOptions.java

Based on https://github.com/appium/appium-android-driver/pull/345

Add bugreport option to Android screen recorder

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/HasAndroidClipboard.java
src/main/java/io/appium/java_client/clipboard/ClipboardContentType.java
src/main/java/io/appium/java_client/clipboard/HasClipboard.java
src/main/java/io/appium/java_client/ios/HasIOSClipboard.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/test/java/io/appium/java_client/android/ClipboardTest.java
src/test/java/io/appium/java_client/ios/ClipboardTest.java

this adds possibility to set and get clipboard content for Android and iOS

Add clipboard handlers

---

build.gradle
src/main/java/io/appium/java_client/AppiumFluentWait.java
src/main/java/io/appium/java_client/events/DefaultAspect.java
src/main/java/io/appium/java_client/events/DefaultListener.java
src/main/java/io/appium/java_client/events/api/general/WindowEventListener.java
src/main/java/io/appium/java_client/pagefactory/AppiumElementLocator.java
src/main/java/io/appium/java_client/pagefactory/AppiumElementLocatorFactory.java
src/main/java/io/appium/java_client/pagefactory/AppiumFieldDecorator.java
src/main/java/io/appium/java_client/pagefactory/TimeOutDuration.java
src/main/java/io/appium/java_client/pagefactory/WidgetInterceptor.java
src/main/java/io/appium/java_client/pagefactory/WidgetListInterceptor.java
src/main/java/io/appium/java_client/pagefactory/WithTimeout.java
src/test/java/io/appium/java_client/android/AndroidFunctionTest.java
src/test/java/io/appium/java_client/android/BaseAndroidTest.java
src/test/java/io/appium/java_client/appium/AppiumFluentWaitTest.java
src/test/java/io/appium/java_client/events/BaseListenerTest.java
src/test/java/io/appium/java_client/events/WebDriverEventListenerCompatibilityTest.java
src/test/java/io/appium/java_client/events/listeners/AppiumListener.java
src/test/java/io/appium/java_client/events/listeners/WindowListener.java
src/test/java/io/appium/java_client/events/listeners/WindowListener2.java
src/test/java/io/appium/java_client/pagefactory_tests/AndroidPageObjectTest.java
src/test/java/io/appium/java_client/pagefactory_tests/DesktopBrowserCompatibilityTest.java
src/test/java/io/appium/java_client/pagefactory_tests/IOSMobileBrowserCompatibilityTest.java
src/test/java/io/appium/java_client/pagefactory_tests/MobileBrowserCompatibilityTest.java
src/test/java/io/appium/java_client/pagefactory_tests/SelendroidModeTest.java
src/test/java/io/appium/java_client/pagefactory_tests/TimeoutTest.java

- FIX of #846. Update to Selenium 3.11
- #846 and #742 fixes. Migration to java.time.Duration
I am sorry for the long break. Was busy.

 #846 and #742 FIX

---

src/main/java/io/appium/java_client/remote/AppiumW3CHttpCommandCodec.java

The previous implementation was crashing in W3C mode, since we always only set `value` argument and selenium hook expects `text` to be set as well while performing parameters amend. W3C spec itself only has `value` description.

Avoid amending parameters for SET_ALERT_VALUE endpoint

---

src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/Connection.java
src/main/java/io/appium/java_client/android/connection/ConnectionState.java
src/main/java/io/appium/java_client/android/connection/ConnectionStateBuilder.java
src/main/java/io/appium/java_client/android/connection/HasNetworkConnection.java
src/test/java/io/appium/java_client/android/AndroidConnectionTest.java

With the previous implementation it was only possible to enable connections, but not disable. I think the current approach will make the feature much more flexible than it was before.

Refactor network connection setting on Android

---

src/main/java/io/appium/java_client/clipboard/HasClipboard.java
src/main/java/io/appium/java_client/ios/HasIOSClipboard.java
src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java

- OkHttpClient instead of ApacheHttpClient
- fix of java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at...
I could reproduce `java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at...` on the getting of clipboard text

Addition to #846 and #855:

---

build.gradle

Use hamcrest-library instead of hamcrest-all dependency. 
`hamcrest-library` is enough to cover functionality required by unit tests, while `hamcrest-all` dependency is excessive. See overview of hamcrest distributables for more details: https://code.google.com/archive/p/hamcrest/wikis/HamcrestDistributables.wiki .

Use hamcrest-library instead of hamcrest-all dependency

---

src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java

Use default Selenium HTTP client factory instead of its particular implementation.
Usage of default Selenium HTTP client factory brings required level of abstraction, clients rely on the same mechanism as for Selenium WD while choosing HTTP client. The implementation used can be changed by setting the `webdriver.http.factory` system property.

Use default Selenium HTTP client factory

---

src/main/java/io/appium/java_client/service/local/flags/GeneralServerFlag.java

Adding the new server arguments for `--relaxed-security` and `--enable-heapdump`

Adding the new server arguments

---

src/main/java/io/appium/java_client/ios/IOSTouchAction.java
src/main/java/io/appium/java_client/ios/touch/IOSPressOptions.java
src/test/java/io/appium/java_client/ios/IOSTouchTest.java

Based on https://github.com/appium/WebDriverAgent/pull/79
This will allow to automate 3D Touch/Force touch scenarios for iOS

Add a possibility to set pressure value for iOS

---

src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/ios/ListensToSyslogMessages.java
src/test/java/io/appium/java_client/ios/IOSSyslogListenerTest.java

Based on https://github.com/appium/appium-xcuitest-driver/pull/653

Support syslog broadcast with iOS

---

src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java
src/main/java/io/appium/java_client/service/local/ListOutputStream.java

It is not always necessary to have all the server logs shown in the system stdout, but currently there is no way to change this default setting (except of via using reflection).

Add a method for output streams cleanup

---

src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/ListensToLogcatMessages.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/ios/ListensToSyslogMessages.java

It looks like web socket lib throws an exception on init for some reason. So it would be safer to init the stuff lazily in order to avoid the java class loader from throwing this exception each time when the driver is instantiated.
See https://stackoverflow.com/questions/50293463/appium-test-case-throws-exception for the reference.

Init web socket clients lazily

---

src/main/java/io/appium/java_client/TouchAction.java

I saw some issue reports where people complain about NPE while the driver instance, which is passed as the constructor argument, equals to `null`. This fix allows to detect the problem on the early stage.

Add TouchAction constructor argument verification

---

src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java
src/main/java/io/appium/java_client/remote/AppiumHttpClientFactory.java

It looks like setting okhttp client to not retry on connection failure by default causes issues while switching contexts (which was previously not the case with apache http client). This PR tries to enforce the default setting to true, but this still requires more testing in the client side, because the problem is not always reproducible.

Set retry flag to true by default for OkHttpFactory

---

src/main/java/io/appium/java_client/HasDeviceTime.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java
src/test/java/io/appium/java_client/ios/IOSDriverTest.java

Now it is possible to explicitly set the format specifiers for the returned datetime. Also, the default response format is changed to ISO-8601

Add an optional format argument to getDeviceTime and update the documentation

---

src/main/java/io/appium/java_client/remote/NewAppiumSessionPayload.java

Fix https://github.com/appium/appium-dotnet-driver/issues/229 
https://github.com/jlipps/simple-wd-spec#processing-capabilities
@dpgraham @mykola-mokhnach ping

 Fix session payload for W3C

---

src/main/java/io/appium/java_client/remote/AppiumW3CHttpCommandCodec.java

Map `sendKeysToActiveElement` to W3C actions. Previously calling `keyboard.sendKeys` would throw an exception, since W3C standard does not declare `sendKeysToActiveElement` endpoint.

Map sending keys to active element for W3C compatibility

---

src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java

Better handling of invocationtargetexception thrown during creating session
Thanks @iddol.
@mykola-mokhnach FYI

better handling of invocationtargetexception

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/FindsByImage.java
src/main/java/io/appium/java_client/MobileBy.java
src/main/java/io/appium/java_client/MobileSelector.java

Based on https://github.com/appium/appium-base-driver/pull/235

Add support for "-image" locator type

---

build.gradle
gradle.properties
src/main/java/io/appium/java_client/internal/Config.java
src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java
src/main/resources/main.properties
src/test/java/io/appium/java_client/internal/ConfigTest.java

Currently users are confused by the error message, which appears on sessions creation. This change should make the error more informative and easier to fix.

Improve the error message on session creation

---

src/main/java/io/appium/java_client/FindsByAndroidViewTag.java
src/main/java/io/appium/java_client/MobileBy.java
src/main/java/io/appium/java_client/MobileSelector.java
src/main/java/io/appium/java_client/android/AndroidDriver.java

Related : appium/appium-espresso-driver#189

#995 add android viewtag for espresso driver

---

src/main/java/io/appium/java_client/InteractsWithFiles.java

JDK9 compatibility: replace `DatatypeConverter.parseBase64Binary(..)` with `Base64.getDecoder().decode(..)`

JDK9 compatibility: replace DatatypeConverter with Base64

---

src/main/java/io/appium/java_client/touch/offset/ElementOption.java
src/main/java/io/appium/java_client/touch/offset/PointOption.java
src/test/java/io/appium/java_client/touch/TouchOptionsTests.java

Expand touch options API to accept coordinates as `org.openqa.selenium.Point`

Expand touch options API to accept coordinates as Point

---

README.md
build.gradle
jitpack.yml

Publish Java client through Jitpack
@mykola-mokhnach @jlipps This PR will allow us to publish java client through jitpack. This will unblock users to use latest commit even before its available in maven central.

Publish Java client through Jitpack

---

build.gradle
src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java
src/main/java/io/appium/java_client/service/local/Slf4jLogMessageContext.java
src/test/java/io/appium/java_client/service/local/AppiumDriverLocalServiceTest.java
src/test/java/io/appium/java_client/service/local/ServerBuilderTest.java

Add possibilty to enable server output data logging through  [SLF4J](http://slf4j.org) loggers. This allow server output data to be configured with your preferred logging frameworks (e.g. java.util.logging, logback, log4j).
**Normal use case:**
```Java
AppiumDriverLocalService service = ...
service.clearOutPutStreams();
service.enableDefaultSlf4jLoggingOfOutputData(); // <-- add this method call
service.start();
```
By default log messages are:
* logged at `INFO` level, unless log message is pre-fixed by `[debug]` then logged at `DEBUG` level.
* logged by a [SLF4J](http://slf4j.org) logger instance with a logger name corresponding to the appium sub module as prefixed in log message (logger name is transformed to lower case, no spaces and prefixed with "appium.service.").
Example of log …

Add SLF4J logging support for Appium local service

---

build.gradle

Use the latest official ECJ 3.14.0
The old ECJ reference was bogus (see official confirmation: https://bugs.eclipse.org/bugs/show_bug.cgi?id=499019#c19) and didn't work properly with JDK9

Use the latest official ECJ 3.14.0

---

src/main/java/io/appium/java_client/pagefactory/HowToUseLocators.java
src/main/java/io/appium/java_client/pagefactory/OverrideWidget.java
src/main/java/io/appium/java_client/pagefactory/SelendroidBy.java
src/main/java/io/appium/java_client/pagefactory/SelendroidFindAll.java
src/main/java/io/appium/java_client/pagefactory/SelendroidFindBy.java
src/main/java/io/appium/java_client/pagefactory/SelendroidFindByAllSet.java
src/main/java/io/appium/java_client/pagefactory/SelendroidFindByChainSet.java
src/main/java/io/appium/java_client/pagefactory/SelendroidFindBySet.java
src/main/java/io/appium/java_client/pagefactory/SelendroidFindBys.java
src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java
src/main/java/io/appium/java_client/service/local/flags/AndroidServerFlag.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/combined/DefaultSelendroidWidget.java

Deprecated Selendroid
http://appium.io/docs/en/drivers/android-selendroid/

deprecate selendroid

---

src/main/java/io/appium/java_client/ios/IOSStartScreenRecordingOptions.java

Based on https://github.com/appium/appium-xcuitest-driver/pull/833

Add new screen recording options for iOS

---

src/main/java/io/appium/java_client/FindsByIosUIAutomation.java
src/main/java/io/appium/java_client/MobileBy.java
src/main/java/io/appium/java_client/pagefactory/HowToUseLocators.java
src/main/java/io/appium/java_client/pagefactory/iOSFindAll.java
src/main/java/io/appium/java_client/pagefactory/iOSFindBy.java
src/main/java/io/appium/java_client/pagefactory/iOSFindByAllSet.java
src/main/java/io/appium/java_client/pagefactory/iOSFindByChainSet.java
src/main/java/io/appium/java_client/pagefactory/iOSFindBySet.java
src/main/java/io/appium/java_client/pagefactory/iOSFindBys.java

Depreacted UIAutomation findBys and findBySets

deprecate UIAutomation for iOS

---

src/main/java/io/appium/java_client/DefaultGenericMobileDriver.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/ios/IOSDriver.java

Add null checks to `getCapabilities()` that prevent spurious null pointer exceptions.
The `capabilities` field in `RemoteWebDriver` remains null until a new session is successfully created.  If something fails before the Selenium client can consolidate the returned capabilities, a `NullPointerException` is thrown from the Appium overriden `getCapabilities` methods that masks the real failure.
In other words:
- Appium [overrides `getCapabilities`][2]
- Selenium first [requests a new session][3], then [saves the returned capabilities][1]
- If the new session command fails, [`getCapabilities` is called][4]
- Because `RemoteWebDriver` returns null, the Appium override [tries to call a …

Avoid null pointer exceptions when calling getCapabilities

---

src/main/java/io/appium/java_client/FindsByAndroidDataMatcher.java
src/main/java/io/appium/java_client/MobileBy.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidElement.java
src/main/java/io/appium/java_client/pagefactory/AndroidFindBy.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/Strategies.java

Add the new location strategy
Based on https://github.com/appium/appium-espresso-driver/pull/386

Add Espresso data-matcher-based location strategy

---

src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java

related to: https://github.com/appium/appium/issues/12234
Send both `signalStrengh` and `signalStrength` as backword compatibility.
The value should be same.
`signalStrength` is also accepted by Appium server after appium/appium-base-driver#308

send both signalStrengh and signalStrength

---

ISSUE_TEMPLATE.md
README.md
docs/How-to-report-an-issue.md
docs/Installing-the-project.md
docs/Note-for-developers.md
docs/Page-objects.md
docs/Tech-stack.md
docs/The-event_firing.md
docs/The-starting-of-an-Android-app.md
docs/The-starting-of-an-app-using-Appium-node-server-started-programmatically.md
docs/The-starting-of-an-iOS-app.md
docs/environment.md

fix #934 
* fix moved or deleted contents
* replace `http` to `https`

fix links in the documents

---

src/main/java/io/appium/java_client/Setting.java
src/main/java/io/appium/java_client/android/HasAndroidSettings.java
src/main/java/io/appium/java_client/ios/HasIOSSettings.java
src/test/java/io/appium/java_client/android/SettingTest.java
src/test/java/io/appium/java_client/ios/SettingTest.java

* add the missing settings which introduced in appium 1.12 and 1.13
* shutdownOnPowerDisconnect
* mjpegScalingFactor
* autoUpdateImageElementPosition
* fixImageTemplateScale
* defaultImageTemplateScale
* fix javadocs
* use https
* fix wrong default values
* add tests

Add the missing settings which introduced in appium 1.12 and 1.13

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/windows/WindowsDriver.java

Addresses https://github.com/appium/java-client/issues/1162
I hope the change won't affect much clients, but the current logic there is anyway incorrect and must be fixed.

Avoid enforcing the platform name while creating drivers

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/ExecutesDriverScript.java
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/driverscripts/ScriptOptions.java
src/main/java/io/appium/java_client/driverscripts/ScriptType.java
src/main/java/io/appium/java_client/driverscripts/ScriptValue.java
src/test/java/io/appium/java_client/android/ExecuteDriverScriptTest.java

Based on https://github.com/appium/appium-base-driver/pull/328

Add executeDriverScript command

---

src/main/java/io/appium/java_client/Setting.java
src/main/java/io/appium/java_client/android/HasAndroidSettings.java
src/main/java/io/appium/java_client/ios/HasIOSSettings.java
src/test/java/io/appium/java_client/android/SettingTest.java
src/test/java/io/appium/java_client/ios/SettingTest.java

add new settings:
* `trackScrollEvents` appium/appium-uiautomator2-server#284
* `keyboardAutocorrection`, `keyboardPrediction` appium/appium#12737
* `getMatchedImageResult` appium/appium-base-driver#327

add the settings which introduced in appium 1.14

---

src/main/java/io/appium/java_client/HasSessionDetails.java
src/main/java/io/appium/java_client/MobileCommand.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java

Code changes for getting all session details

---

src/main/java/io/appium/java_client/ios/IOSStartScreenRecordingOptions.java

Based on https://github.com/appium/appium-xcuitest-driver/pull/1005

Add videoFilters property to the video recording params

---

src/main/java/io/appium/java_client/pagefactory/bys/builder/AppiumByBuilder.java
src/main/java/io/appium/java_client/remote/AutomationName.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/android/AndroidApp.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/android/AnnotatedAndroidWidget.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/android/DefaultAndroidWidget.java

Deprecate Selendroid AutomationName - https://github.com/appium/appium/issues/12871 

Mark Selendroid AutomationName as deprecated

---

src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java
src/main/java/io/appium/java_client/remote/IOSMobileCapabilityType.java
src/main/java/io/appium/java_client/remote/MobileCapabilityType.java

Update javadoc of capabilities to follow latest Appium documents.
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md
and
https://github.com/appium/appium-xcuitest-driver/blob/master/README.md#desired-capabilities
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on …

Update javadoc of capabilities to follow latest Appium documents

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/internal/CapabilityHelpers.java
src/main/java/io/appium/java_client/internal/ElementMap.java
src/main/java/io/appium/java_client/internal/JsonToMobileElementConverter.java
src/main/java/io/appium/java_client/pagefactory/AppiumFieldDecorator.java
src/main/java/io/appium/java_client/pagefactory/utils/WebDriverUnpackUtility.java
src/main/java/io/appium/java_client/remote/NewAppiumSessionPayload.java
src/test/java/io/appium/java_client/ios/IOSNativeWebTapSettingTest.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/AbstractStubWebDriver.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/ExtendedWidgetTest.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/android/AndroidWidgetTest.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/ios/XCUITWidgetTest.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/windows/WindowsWidgetTest.java
src/test/java/io/appium/java_client/service/local/StartingAppLocallyTest.java

W3C protocol does not contain getSession API in its spec, which means all calls to `HasSessionDetails` interface methods will end up with `no such method` error. As a result, I have replaced all the "static" calls  with simple capabilities extraction and the "dynamic" call uses the fact that none of native mobile drivers support javascript execution, - this only works in browser context.
See https://github.com/appium/appium/issues/13124#issuecomment-524850823

fix: Avoid using getSession call for capability values retrieval

---

src/main/java/io/appium/java_client/android/HasAndroidDeviceDetails.java

Addresses https://github.com/appium/java-client/issues/1228

fix: Fix the return type for getSystemBars call

---

src/main/java/io/appium/java_client/InteractsWithApps.java
src/main/java/io/appium/java_client/ios/IOSDriver.java

https://github.com/appium/appium-xcuitest-driver/pull/1064

chore: Switch the implementation of backgroundApp for iOS, so it's in sync with other platforms

---

src/main/java/io/appium/java_client/HasSettings.java
src/main/java/io/appium/java_client/MobileCommand.java
src/test/java/io/appium/java_client/android/SettingTest.java
src/test/java/io/appium/java_client/ios/SettingTest.java

Java-client Setting API `setSetting(Setting, Object)` only accepts enum `Setting`. It's good for type safe. But, when new settings are added on server, user cannot use it until client update.  I think this API should be more flexible. 
I propose that Setting API can also accept String type like capabilities.
About markdown please read [Mastering …

Setting API should accept String type

---

src/main/java/io/appium/java_client/HasSettings.java

Recently Appium started retuning `null` as setting value. This breaks ImmutableMap implementation, which does not allow nulls as values.
Addresses https://dev.azure.com/srinivasansekar/java-client/_build/results?buildId=290&view=ms.vss-test-web.build-test-results-tab&runId=1000428&resultId=100049&paneView=debug

fix: Avoid throwing null pointer exception if any of settings is equal to null

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/LogsEvents.java
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/serverevents/CommandEvent.java
src/main/java/io/appium/java_client/serverevents/CustomEvent.java
src/main/java/io/appium/java_client/serverevents/ServerEvents.java
src/main/java/io/appium/java_client/serverevents/TimedEvent.java
src/test/java/io/appium/java_client/android/BaseAndroidTest.java
src/test/java/io/appium/java_client/android/LogEventTest.java

Depends on https://github.com/appium/appium-base-driver/pull/364
(I couldn't get tests to run due to some Class Not Found error that seems unrelated.)

feat: add support for logCustomEvent command

---

ISSUE_TEMPLATE.md

Modified typo/grammar/wording of Issue Template

Improve Readability of Issue Template

---

src/main/java/io/appium/java_client/service/local/flags/GeneralServerFlag.java

* Add allow-insecure server flag.
* Add deny-insecure server flag.

Add allow-insecure and deny-insecure server flags

---

src/test/java/io/appium/java_client/ios/BaseIOSWebViewTest.java

This PR is supposed to address https://dev.azure.com/srinivasansekar/java-client/_build/results?buildId=338&view=logs

chore: Update web view detection algorithm for iOS tests

---

src/main/java/io/appium/java_client/FindsByAndroidViewMatcher.java
src/main/java/io/appium/java_client/MobileBy.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidElement.java
src/main/java/io/appium/java_client/events/DefaultAspect.java
src/main/java/io/appium/java_client/pagefactory/AndroidFindBy.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/Strategies.java
src/test/java/io/appium/java_client/android/AndroidDataMatcherTest.java
src/test/java/io/appium/java_client/android/AndroidViewMatcherTest.java
src/test/java/io/appium/java_client/android/BaseEspressoTest.java

Per [appium/appium#13747](https://github.com/appium/appium/issues/13747), add support for viewmatcher along with test for datamatcher 
Similar to dataMatcher, provides a functionality for viewMatcher. Also I noticed that dataMatcher had no test, so I added one for dataMatcher as well.

Feat: Add support for viewmatcher

---

build.gradle

https://docs.gradle.org/6.0/release-notes.html#javadoc-sources-jar
Use Gradle 6 built-in support for javadoc and source jars
https://docs.gradle.org/6.0/release-notes.html#javadoc-sources-jar

chore: Use Gradle 6 built-in support for javadoc and source jars

---

azure-pipelines.yml
src/main/java/io/appium/java_client/android/AndroidStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/ios/IOSStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/BaseScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/BaseStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/CanRecordScreen.java
src/main/java/io/appium/java_client/windows/WindowsDriver.java
src/main/java/io/appium/java_client/windows/WindowsStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/windows/WindowsStopScreenRecordingOptions.java
src/test/java/io/appium/java_client/appium/element/generation/BaseElementGenerationTest.java
src/test/java/io/appium/java_client/appium/element/generation/android/AndroidElementGeneratingTest.java
src/test/java/io/appium/java_client/appium/element/generation/ios/IOSElementGenerationTest.java
src/test/java/io/appium/java_client/ios/AppIOSTest.java
src/test/java/io/appium/java_client/ios/BaseIOSWebViewTest.java

Based on https://github.com/appium/appium-windows-driver/pull/66

feat: Add wrappers for the Windows screen recorder

---

azure-pipelines.yml
src/test/java/io/appium/java_client/ios/IOSAlertTest.java
src/test/java/io/appium/java_client/ios/IOSTouchTest.java
src/test/java/io/appium/java_client/pagefactory_tests/XCUITModeTest.java

...this is the nice example of why to always use dedicated types for different time units
https://dev.azure.com/srinivasansekar/java-client/_build/results?buildId=376&view=logs&j=dcf5f1f5-2eb6-5586-dc7f-e40285fb9e33&t=001cc609-8f94-5735-fd9e-04c1a9cbbffb

fix: Set appropriate fluent wait timeouts

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/HasSettings.java
src/main/java/io/appium/java_client/android/HasAndroidSettings.java
src/main/java/io/appium/java_client/ios/HasIOSSettings.java
src/test/java/io/appium/java_client/ios/IOSAlertTest.java

It makes sense to make settings available for all AppiumDriver descendants by default, since on the server side the API is declared in base-driver, which means it works for all Appium drivers

feat: Make settings available for all AppiumDriver instances

---

src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java

* Add support for Android capability types: `buildToolsVersion`, `enforceAppInstall`, `ensureWebviewsHavePages`, `webviewDevtoolsPort`, and `remoteAppsCacheLimit`.
Just adding things I see in documentation that aren't in the capabilities file.
Along these lines, what do you think about adding the UIAutomator2 capabilities to this file??
https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/caps.md#uiautomator2-only

update android capability types

---

src/main/java/io/appium/java_client/remote/MobileCapabilityType.java

- Removed appiumVersion from MobileCapabilityType
The capability `appiumVersion` is a Sauce specific capability.
This should not be included in the Java bindings since Appium does not do anything with this capability and should be handled either manually by the user or via some other third party tool.
This fixes this being included on the Appium Java client.

fix: remove appiumVersion from MobileCapabilityType

---

src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java

This PR adds a random idempotency key to each session creation request. This is necessary to properly handle HTTP request retries. Read https://github.com/appium/appium-base-driver/pull/400 for more details.

feat: Add idempotency key to session creation requests

---

src/main/java/io/appium/java_client/HasDeviceTime.java

Selenium webdriver implementation ignores parameters passed into GET requests. This PR replaces the call with parameters with the corresponding `mobile:` endpoint implementation to make it working properly. See https://github.com/appium/appium/issues/14141

chore: Change getDeviceTime to call the `mobile` implementation

---

src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java
src/test/java/io/appium/java_client/service/local/ServerBuilderTest.java

Addresses https://github.com/appium/java-client/issues/1336

fix: Properly translate desiredCapabilities into a command line argument

---

src/main/java/io/appium/java_client/screenrecording/ScreenRecordingUploadOptions.java

feat: Add new upload options that were introduced recently

---

src/main/java/io/appium/java_client/touch/offset/ElementOption.java
src/test/java/io/appium/java_client/touch/TouchOptionsTests.java

* instead, cast to interface HasIdentity (because it's a weaker type).
* this commit is similar to https://github.com/appium/java-client/pull/432/files
Some background: as a developer of framework which uses proxies for WebElement (Selenide), I cannot create proxy for RemoteWebElement since it's an abstract class, not interface.
work and possible use cases. Also you can create [gists](https://gist.github.com) with pasted java code samples or put them here using markdown. …

refactor: avoid casting to RemoteWebElement

---

build.gradle
src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java

The previous warnings list has about 170 items. This is confusing and is hard to read. Now we only have 9 and most of these are meaningful.

chore: Mute all confusing warnings

---

src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java

Selenium lib hardcodes the graceful shutdown timeout to 2 seconds (zero on Windows). This is not enough for Appium to properly shutdown all the drivers and clean up the leftovers.

fix: Increase the timeout for graceful service termination

---

src/main/java/io/appium/java_client/ComparesImages.java
src/main/java/io/appium/java_client/battery/BatteryInfo.java
src/main/java/io/appium/java_client/imagecomparison/ComparisonResult.java
src/main/java/io/appium/java_client/internal/CapabilityHelpers.java
src/main/java/io/appium/java_client/internal/Config.java
src/main/java/io/appium/java_client/pagefactory/utils/ProxyFactory.java
src/main/java/io/appium/java_client/remote/NewAppiumSessionPayload.java
src/main/java/io/appium/java_client/screenrecording/CanRecordScreen.java
src/main/java/org/openqa/selenium/SearchContext.java

docs: Address warnings printed by docs linter

---

docs/environment.md

docs: Update environment troubleshooting

---

azure-pipelines.yml
src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/internal/CapabilityHelpers.java
src/main/java/io/appium/java_client/internal/JsonToMobileElementConverter.java
src/main/java/io/appium/java_client/pagefactory/AppiumFieldDecorator.java
src/test/java/io/appium/java_client/ios/IOSTouchTest.java

Related to https://github.com/appium/java-client/issues/1275
I don't know the reason why to pass enum value instead of a string as platformName, like this is required by the standard, but whatever. The fix should just make it working for both cases.

fix: Parse platformName if it is passed as enum item

---

build.gradle
src/test/java/io/appium/java_client/service/local/ServerBuilderTest.java
src/test/java/io/appium/java_client/service/local/StartingAppLocallyTest.java

update Gradle and fix Jitpack build failures

build: update gradle and fix jitpack build failures

---

src/main/java/io/appium/java_client/HasSettings.java
src/main/java/io/appium/java_client/MobileCommand.java
src/test/java/io/appium/java_client/android/SettingTest.java
src/test/java/io/appium/java_client/ios/SettingTest.java

Add ability to set multiple settings to avoid performance overhead when several changes are required to be done at once.

feat: Add ability to set multiple settings

---

src/main/java/io/appium/java_client/internal/ElementMap.java

Fixes #965 
Fixes #774
Fixes #1247

fix: Use lower case for Windows platform key in ElementMap

---

src/main/java/io/appium/java_client/mac/FindsByClassChain.java
src/main/java/io/appium/java_client/mac/FindsByNsPredicate.java
src/main/java/io/appium/java_client/mac/Mac2Driver.java
src/main/java/io/appium/java_client/mac/Mac2Element.java
src/main/java/io/appium/java_client/mac/Mac2StartScreenRecordingOptions.java
src/main/java/io/appium/java_client/mac/Mac2StopScreenRecordingOptions.java
src/main/java/io/appium/java_client/remote/MobilePlatform.java

This is a wrapper over [Mac2Driver](https://github.com/appium/appium-mac2-driver)
cc @ki4070ma @akinsolb

feat: Add Mac2Driver

---

src/main/java/io/appium/java_client/imagecomparison/OccurrenceMatchingOptions.java
src/main/java/io/appium/java_client/imagecomparison/OccurrenceMatchingResult.java

Based on https://github.com/appium/appium-base-driver/pull/449

feat: Add support of multiple image occurrences

---

src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java

- Bring back automatic quote escaping for desired capabilities command line arguments on windows
Escaped quotes are necessary for starting appium from the command line on windows systems (see http://appium.io/docs/en/writing-running-appium/default-capabilities-arg/). 
This capability to automatically quote on windows systems was completely removed with commit #1337. Since #1336 discovered a special case where automatic quote escaping on windows was not possible. That means, that windows users now need to manually escape the JSON such as:
```
DesiredCapabilities cap = new DesiredCapabilities();
cap.setCapability("\"platformName\"", "\"Android\"");
AppiumServiceBuilder builder = new …
```

fix: bring back ability to automatically quote desired capabilities on win

---

src/main/java/io/appium/java_client/internal/ElementMap.java

Bind MAC platform with Mac2Element to fix ClassCastException while Mac2Driver usage

fix: bind mac2element in element map for mac platform

---

src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/geolocation/AndroidGeoLocation.java
src/main/java/io/appium/java_client/android/geolocation/SupportsExtendedGeolocationCommands.java

Adds an API that allows to also provide `speed` and `satellites` parameters for setGeolocation API on Android platform
Based on https://github.com/appium/appium-adb/pull/571

feat: Add support of extended Android geolocation

---

.github/dependabot.yml

Enable Dependabot for GitHub actions: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot
Use Dependabot to keep the actions updated to the latest versions.

chore: Enable Dependabot for GitHub actions

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java
src/test/java/io/appium/java_client/ios/AppIOSTest.java
src/test/java/io/appium/java_client/ios/BaseIOSTest.java
src/test/java/io/appium/java_client/ios/IOSDriverTest.java

Appium 2.0 will allow custom plugins to add their own endpoint. This feature helps add custom commands dynamically. 
```
driver.addCommand(HttpMethod.GET, "/sessions", "getSessions");
driver.execute("getSessions");
```

feat: allow to add custom command dynamically

---

src/main/java/io/appium/java_client/service/local/flags/GeneralServerFlag.java

Added new flags to support Appium 2.0

feat: Add new flags to support Appium 2.0

---

.github/workflows/gradle.yml
azure-pipelines.yml

The exclusion of Gradle task `signMavenJavaPublication` from build process in CI is not needed anymore.

build: remove redundant exclusion of Gradle task `signMavenJavaPublication`

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/mac/Mac2Driver.java
src/main/java/io/appium/java_client/windows/WindowsDriver.java

Just some small refactoring to make the stuff look better before adding new driver classes

refactor: Tune setting of default platform names

---

src/main/java/io/appium/java_client/PerformsTouchActions.java
src/main/java/io/appium/java_client/TouchAction.java
src/main/java/io/appium/java_client/android/AndroidTouchAction.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/ios/IOSTouchAction.java
src/main/java/io/appium/java_client/mac/Mac2Driver.java
src/main/java/io/appium/java_client/windows/WindowsDriver.java

Touch actions specification is not part of W3C and has been effectively replaced by [W3C Actions](https://www.w3.org/TR/webdriver/#actions) spec. 
The same change has been already done for Python and Ruby clients.

chore: Deprecate touch actions

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/gecko/GeckoDriver.java
src/main/java/io/appium/java_client/gecko/options/GeckoOptions.java
src/main/java/io/appium/java_client/gecko/options/SupportsAndroidStorageOption.java
src/main/java/io/appium/java_client/gecko/options/SupportsMarionettePortOption.java
src/main/java/io/appium/java_client/gecko/options/SupportsMozFirefoxOptionsOption.java
src/main/java/io/appium/java_client/gecko/options/SupportsSystemPortOption.java
src/main/java/io/appium/java_client/gecko/options/SupportsVerbosityOption.java
src/main/java/io/appium/java_client/gecko/options/Verbosity.java
src/main/java/io/appium/java_client/remote/options/BaseOptions.java
src/main/java/io/appium/java_client/remote/options/SupportsAcceptInsecureCertsOption.java
src/main/java/io/appium/java_client/remote/options/SupportsBrowserVersionOption.java
src/main/java/io/appium/java_client/remote/options/SupportsClearSystemFilesOption.java
src/main/java/io/appium/java_client/remote/options/SupportsLanguageOption.java
src/main/java/io/appium/java_client/remote/options/SupportsPageLoadStrategyOption.java
src/main/java/io/appium/java_client/remote/options/SupportsProxyOption.java
src/main/java/io/appium/java_client/remote/options/SupportsSetWindowRectOption.java
src/main/java/io/appium/java_client/remote/options/SupportsUnhandledPromptBehaviorOption.java
src/main/java/io/appium/java_client/remote/options/UnhandledPromptBehavior.java

https://github.com/appium/appium-geckodriver

feat: Add Gecko driver options

---

src/main/java/io/appium/java_client/safari/SafariDriver.java
src/main/java/io/appium/java_client/safari/options/SafariOptions.java
src/main/java/io/appium/java_client/safari/options/SupportsSafariAutomaticInspectionOption.java
src/main/java/io/appium/java_client/safari/options/SupportsSafariAutomaticProfilingOption.java
src/main/java/io/appium/java_client/safari/options/SupportsSafariDeviceNameOption.java
src/main/java/io/appium/java_client/safari/options/SupportsSafariDeviceTypeOption.java
src/main/java/io/appium/java_client/safari/options/SupportsSafariDeviceUdidOption.java
src/main/java/io/appium/java_client/safari/options/SupportsSafariPlatformBuildVersionOption.java
src/main/java/io/appium/java_client/safari/options/SupportsSafariPlatformVersionOption.java
src/main/java/io/appium/java_client/safari/options/SupportsSafariUseSimulatorOption.java
src/main/java/io/appium/java_client/safari/options/SupportsWebkitWebrtcOption.java
src/main/java/io/appium/java_client/safari/options/WebrtcData.java
src/test/java/io/appium/java_client/drivers/options/OptionsBuildingTest.java

Added Safari driver options with some basic tests

feat: Add Safari driver options

---

src/main/java/io/appium/java_client/pagefactory/DefaultElementByBuilder.java
src/main/java/io/appium/java_client/pagefactory/bys/ContentType.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/AppiumByBuilder.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/ByChained.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/HowToUseSelectors.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/Strategies.java

Just to make it looking nicer.

refactor: Add more nice functional stuff into pagefactory helpers

---

.azure-templates/bootstrap_steps.yml
azure-pipelines.yml
docs/v7-to-v8-migration-guide.md
src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java
src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java
src/main/java/io/appium/java_client/service/local/flags/GeneralServerFlag.java
src/test/java/io/appium/java_client/android/BaseAndroidTest.java
src/test/java/io/appium/java_client/ios/AppIOSTest.java
src/test/java/io/appium/java_client/ios/BaseIOSTest.java
src/test/java/io/appium/java_client/ios/BaseIOSWebViewTest.java
src/test/java/io/appium/java_client/ios/BaseSafariTest.java
src/test/java/io/appium/java_client/service/local/ServerBuilderTest.java

Appium 1 will be dropped soon, so we need to make sure all tests are working as expected
BREAKING CHANGE: Updated command line args to comply with Appium 2.0
BREAKING CHANGE: The default local service URL does not contain the `/wd/hub` prefix anymore
- [] No changes in production code.

refactor!: Switch e2e tests to use Appium2

---

build.gradle

In a favor of flexibility the constraints of selenium dependencies versions are relaxed.
https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html: "conflicting strict dependencies will trigger a build failure that you have to resolve".
An attempt to use `java-client:8.0.0-beta` in conjunction with Selenium 4.1.0 leads to build failures, like:
```
> Could not resolve org.seleniumhq.selenium:selenium-remote-driver:{strictly 4.0.0}.
Required by:
project :xxxxxxx > io.appium:java-client:8.0.0-beta
```
In a favor of flexibility the constraints of selenium dependencies versions are relaxed.

build: relax constraints of Selenium dependencies versions

---

gradle.properties

Fixes #1608.
Bump Selenium from `4.0.0` to `4.1.1`
Selenium `4.1.1` contains bug fix: HttpClient follows redirects by default. This fix is crucial for some cloud testing providers.

fix: bump Selenium from `4.0.0` to `4.1.1`

---

src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java

fix  #1617
avoid chinese garbled characters 
details  #1617

fix: chinese garbled characters #1617

---

src/main/java/io/appium/java_client/AppiumBy.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/Strategies.java

Addresses https://github.com/appium/java-client/issues/1621

fix: Avoid fallback to css for id and name locator annotations

---

src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java

Argument names are case sensitive, so there is no sense in this conversion, it only adds more potential issues.

fix: Do not convert argument names to lowercase

---

docs/Installing-the-project.md

on my machine, Maven defaults to 1.7, which doesn't work. add instructions to update the version in `pom.xml`.
on my Maven (and I _think_ everyone's?), the default java.compiler.source and java.compiler.target are 1.7, which doesn't work on my machine.

Change the java version

---

src/main/java/io/appium/java_client/android/HasAndroidSettings.java
src/main/java/io/appium/java_client/ios/HasIOSSettings.java

Addresses https://github.com/appium/java-client/issues/1643

fix: Make interfaces public to fix decorator creation

---

README.md

docs: Add a note about the client code migration

---

src/main/java/io/appium/java_client/pagefactory/ElementInterceptor.java
src/main/java/io/appium/java_client/pagefactory/ElementListInterceptor.java
src/main/java/io/appium/java_client/pagefactory/utils/WebDriverUnpackUtility.java

Delete confusing references to removed `MobileElement` class from JavaDocs and comments.

chore: delete all references to removed `MobileElement` class

---

src/main/java/io/appium/java_client/android/options/server/EspressoBuildConfig.java

https://github.com/appium/java-client/issues/1678

chore: Add new EspressoBuildConfig options

---

build.gradle
gradle.properties
src/main/java/io/appium/java_client/remote/AppiumNewSessionCommandPayload.java
src/main/java/io/appium/java_client/remote/options/BaseOptions.java
src/test/java/io/appium/java_client/android/AndroidDataMatcherTest.java
src/test/java/io/appium/java_client/android/OpenNotificationsTest.java
src/test/java/io/appium/java_client/ios/IOSAlertTest.java

chore: Bump minimum selenium api version to 4.2.0

---

src/main/java/io/appium/java_client/remote/AppiumNewSessionCommandPayload.java
src/main/java/io/appium/java_client/remote/options/BaseOptions.java
src/main/java/io/appium/java_client/remote/options/W3CCapabilityKeys.java

Addresses https://github.com/appium/java-client/issues/1701#issuecomment-1144228448

fix: Add prefix to platformVersion capability name

---

src/main/java/io/appium/java_client/remote/options/W3CCapabilityKeys.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/AbstractStubWebDriver.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/combined/CombinedAppTest.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/combined/CombinedWidgetTest.java
src/test/java/io/appium/java_client/service/local/StartingAppLocallyAndroidTest.java

Update e2e tests and make it green 💚

test: Update e2e tests

---

src/main/java/io/appium/java_client/mac/options/SupportsEnvironmentOption.java

fix: Update the environment argument type

---

azure-pipelines.yml

Update Azure pipeline config to use `macos-11` VM image
The current VM image is deprecated:

ci: update Azure pipeline to use `macos-11` VM image

---

gradle.properties
src/main/java/io/appium/java_client/remote/AppiumW3CHttpCommandCodec.java

Fixes #1694
Selenium `4.4.0` contains fixes for #1694

fix: Bump minimum required Selenium version to `4.4.0`

---

src/main/java/io/appium/java_client/pagefactory/DefaultElementByBuilder.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/AppiumByBuilder.java
src/main/java/io/appium/java_client/pagefactory/bys/builder/ByAll.java

Deprecate Appium `ByAll` in favour of Selenium `ByAll`
Appium `io.appium.java_client.pagefactory.bys.builder.ByAll` was implemented as an extension of Selenium `org.openqa.selenium.support.pagefactory.ByAll` and introduced a performance improvement: "By All was re-implemented, now it returns the first founded element for single search." (https://github.com/appium/java-client/pull/686 on 3 Aug 2017).
However Selenium team introduced the same performance fix "https://github.com/SeleniumHQ/selenium/commit/18028ac9f065b81fbe99a9e84feabfa5d0091f13 ByAll.findElement should not not use remaining locators if an element is already found" on 7 Sep 2017.
So there is no reason to keep Appium …

refactor: Deprecate Appium `ByAll`

---

src/test/java/io/appium/java_client/android/AndroidContextTest.java
src/test/java/io/appium/java_client/android/AndroidFunctionTest.java
src/test/java/io/appium/java_client/internal/ConfigTest.java
src/test/java/io/appium/java_client/ios/IOSContextTest.java
src/test/java/io/appium/java_client/pagefactory_tests/AndroidPageObjectTest.java
src/test/java/io/appium/java_client/service/local/ServerBuilderTest.java

Clean up unit tests asserting thrown exceptions
This PR removes redundant (never invoked) clauses from unit tests asserting thrown exceptions.

test: Clean up unit tests asserting thrown exceptions

---

build.gradle
src/test/java/io/appium/java_client/android/OpenNotificationsTest.java

Test openNotification was failing because on the current version 'settings_button' is not visible, so added check for different element. Also add the test to CI.

test: fix open notification test

---

build.gradle
src/main/java/io/appium/java_client/ComparesImages.java
src/main/java/io/appium/java_client/PushesFiles.java
src/main/java/io/appium/java_client/imagecomparison/ComparisonResult.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java
src/test/java/io/appium/java_client/android/ImagesComparisonTest.java
src/test/java/io/appium/java_client/ios/ImagesComparisonTest.java

Enforce usage of Base64 encoding scheme compliant with `RFC 4648` for all operations (instead of `RFC 2045`).
I'm not sure whether it's really necessary. However the wave of conversations around encoding of screenshots makes me think that following single standard ([W3C WebDriver spec sticks to `RFC 4648`](https://www.w3.org/TR/webdriver/#index)) for all operations will be more consistent approach.

fix: Enforce usage of Base64 compliant with RFC 4648 for all operations

---

src/main/java/io/appium/java_client/AppiumDriver.java

Addresses https://github.com/SeleniumHQ/selenium/issues/11168

fix: Override getScreenshotAs to support the legacy base64 encoding

---

src/main/java/io/appium/java_client/remote/DirectConnect.java

Left TODO to use `lombok` to define getters
Use Lumbok to define getters

chore: use Lombok

---

src/main/java/io/appium/java_client/remote/DirectConnect.java

The accessors annotation can be removed when it has no arguments.
```
> Task :compileJava
/Users/kazu/GitHub/java-client/src/main/java/io/appium/java_client/remote/DirectConnect.java:16: warning: Accessors on its own does nothing. Set at least one parameter
@Accessors
^
```
It seems like the annotation is used only when we'd like to set non-default options
https://github.com/projectlombok/lombok/blob/560ded50127b12bd8168f8ae2bada47253f15bc8/src/core/lombok/core/AnnotationValues.java#L570
(i have tested without this annotation)

chore: remove unnecessary annotation

---

.github/workflows/publish.yml
build.gradle
gradle.properties

ci: fix automated maven repository publishing

---

gradle.properties
src/main/java/io/appium/java_client/remote/AppiumProtocolHandshake.java
src/main/java/io/appium/java_client/remote/SupportsRotation.java
src/test/java/io/appium/java_client/events/stubs/EmptyWebDriver.java

Related to https://github.com/SeleniumHQ/selenium/issues/11347

chore: Bump Selenium version to 4.7.0

---

src/main/java/io/appium/java_client/android/ListensToLogcatMessages.java

On some systems `localhost` is resolved to `::1`, which won'y work for as a proper default

fix: Use ipv4 address instead of localhost

---

src/main/java/io/appium/java_client/remote/IOSMobileCapabilityType.java

This PR removes tapWithShortPressDuration cap.
see https://github.com/appium/appium-xcuitest-driver/pull/1481
see https://github.com/appium/appium-xcuitest-driver/pull/1481

chore: deprecate tapWithShortPressDuration cap

---

.github/workflows/gradle-wrapper-validation.yml

It's not needed to validate Gradle wrapper for each and every change, it should be enough to run it only if particualr Gradle files are changed.

ci: Run Gradle wrapper validation only on Gradle files changes

---

README.md
docs/transitive-dependencies-management.md

Document transitive Selenium dependencies management approaches.
Resolves #1823

docs: Describe transitive Selenium dependencies management

---

build.gradle

Overridden Selenium package was dropped some time ago, but Checkstyle exclusion wasn't deleted. Now it's time to removed leftovers.

build: Remove Checkstyle exclusion of removed Selenium package

---

src/main/java/io/appium/java_client/proxy/Interceptor.java

Improve performance of proxy `Interceptor` logging

perf: Improve performance of proxy `Interceptor` logging

---

build.gradle

JaCoCo 0.8.8 officially supports Java 17 which is used in CI matrix: https://github.com/jacoco/jacoco/releases/tag/v0.8.8.
Usage of JaCoCo 0.8.5 on Java 17 causes errors like:
```
> Task :test
at org.jacoco.agent.rt.internal_43f5073.CoverageTransformer.transform(CoverageTransformer.java:94)
at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:541)
at java.base/java.lang.ClassLoader.defineClass2(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:182) …
```

build: Bump JaCoCo from `0.8.5` to `0.8.8`

---

.github/workflows/gradle.yml
azure-pipelines.yml
build.gradle
jitpack.yml

This change simplifies unit tests task management and execution:
- `test` task of type `Test` is created automatically
- in comparison with previous approach no need to invoke extra task (it was `unitTest`): whenever `build` task is run, `test` task will be executed (this happens because `test` task is attached to the `check` lifecycle task)
More details: https://docs.gradle.org/current/userguide/java_testing.html#sec:java_testing_basics
Also now:
- JitPack build is failed if unit tests fail: no reason to publish invalid build
- Successful run of unit tests is a mandatory prerequisite for execution of integration Android and iOS tests 

build: Make unit tests execution a part of Gradle build lifecycle

---

src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java

https://github.com/appium/java-client/issues/1877

fix: Avoid NPE in destroyProcess call

---

gradle.properties
src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java
src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java

Due to the [breaking change](https://github.com/appium/java-client/issues/1872#issuecomment-1494233769) in the recent Selenium client release we need to update the service builder class to make it great again.

chore: Bump the minimum selenium client version to 4.8.2

---

src/main/java/io/appium/java_client/CommandExecutionHelper.java
src/main/java/io/appium/java_client/InteractsWithApps.java
src/main/java/io/appium/java_client/MobileCommand.java

Eventually we should avoid creating wrappers for non-W3C-compatible endpoints as these endpoints are mostly legacy from mobile-specific commands. We should only provide `mobile:` extension for these.
I don't want to remove existing wrappers though as this could create extra headaches for clients. These should work same way as before, but call corresponding extensions under the hood.
I would say it makes sense to introduce similar changes to other clients as well (e.g. Python/Dotnet/Ruby)
cc @KazuCocoa @jlipps @dor-bl

refactor: Replace non-W3C API  calls with corresponding extension calls in app management

---

src/main/java/io/appium/java_client/CommandExecutionHelper.java
src/main/java/io/appium/java_client/HasDeviceTime.java

Similar to https://github.com/appium/java-client/pull/1883

refactor: Switch the time getter to use mobile extensions

---

src/main/java/io/appium/java_client/InteractsWithApps.java

It looks like the recent server implementation [is not happy](https://dev.azure.com/srinivasansekar/java-client/_build/results?buildId=1666&view=logs&j=61693eb6-c6c2-5404-693f-d0c9a515c613&t=2ca172d0-7775-512d-edc4-316d6d6b3014&l=3205) when we send some extra parameters as args. I've created a [patch](https://github.com/appium/appium/pull/18575) for that, but I would also like to have a working implementation until the patch is applied

fix: Send arguments for mobile methods depending on the target platform

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/AuthenticatesByFinger.java
src/main/java/io/appium/java_client/android/CanReplaceElementValue.java
src/main/java/io/appium/java_client/android/HasAndroidDeviceDetails.java
src/main/java/io/appium/java_client/android/StartsActivity.java
src/main/java/io/appium/java_client/android/SupportsSpecialEmulatorCommands.java
src/test/java/io/appium/java_client/android/AndroidDriverTest.java

feat: Switch more Android helpers to use extensions

---

azure-pipelines.yml

Prebuilding WDA should speed up following iOS tests and make then more stable

ci: Perform xcuitest driver prebuild

---

src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/CanReplaceElementValue.java
src/main/java/io/appium/java_client/android/HasNotifications.java
src/main/java/io/appium/java_client/android/SupportsGpsStateManagement.java

Also fixed the args for replaceValue call

refactor: Finish migrating Android helpers to mobile extensions

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/CanRememberExtensionPresence.java
src/main/java/io/appium/java_client/HasAppStrings.java
src/main/java/io/appium/java_client/HasOnScreenKeyboard.java
src/main/java/io/appium/java_client/HidesKeyboard.java
src/main/java/io/appium/java_client/HidesKeyboardWithKeyName.java
src/main/java/io/appium/java_client/InteractsWithApps.java
src/main/java/io/appium/java_client/LocksDevice.java
src/main/java/io/appium/java_client/android/AuthenticatesByFinger.java
src/main/java/io/appium/java_client/android/CanReplaceElementValue.java
src/main/java/io/appium/java_client/android/HasAndroidDeviceDetails.java
src/main/java/io/appium/java_client/android/HasNotifications.java
src/main/java/io/appium/java_client/android/StartsActivity.java
src/main/java/io/appium/java_client/android/SupportsGpsStateManagement.java
src/main/java/io/appium/java_client/android/SupportsNetworkStateManagement.java
src/main/java/io/appium/java_client/android/SupportsSpecialEmulatorCommands.java
src/main/java/io/appium/java_client/android/connection/HasNetworkConnection.java
src/main/java/io/appium/java_client/android/nativekey/PressesKey.java
src/main/java/io/appium/java_client/ios/ShakesDevice.java

As @KazuCocoa mentioned in https://github.com/appium/python-client/pull/856#issuecomment-1529498871 the change could slow down user scripts, especially if the server runs in cloud env, and we send two requests instead of one (e.g. the server is running an older driver version which does not support the given `mobile` endpoint yet).
In such case we want to remember if the given API is actually supported by the given driver instance, so next time we don't need to call the server twice, and thus save some time on each request.

chore: Avoid sending unnecessary requests if corresponding extensions are absent

---

src/main/java/io/appium/java_client/android/HasSupportedPerformanceDataType.java

Based on https://github.com/appium/appium-uiautomator2-driver/pull/613

refactor: Replace performance data APIs with mobile extensions

---

gradle.properties
src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java

Selenium 4.9.1 introduced 2 breaking changes that cause compilation errors:
- https://github.com/SeleniumHQ/selenium/commit/66e51be38cbd492c11605397e1b50c1cb786a579
- https://github.com/SeleniumHQ/selenium/commit/3d8c6fa7a950ce129f4bd8fb347c71a2cdd4bf07
Make Appium Java client compatible with the newest Selenium client

chore: Bump minimum Selenium client version to 4.9.1

---

src/main/java/io/appium/java_client/PullsFiles.java
src/main/java/io/appium/java_client/PushesFiles.java

Add fallback commands for file management APIs if mobile extensions are not available

fix: Add fallback commands for file management APIs

---

src/main/java/io/appium/java_client/PullsFiles.java

Use correct exception type for fallback at file/folder pulling. The issue was introduced by #1910: wrong exception type was used accidentally.

fix: Use correct exception type for fallback at file/folder pulling

---

README.md

Initiate Selenium client compatibility matrix (to avoid issues like #1914)

docs: Initiate Selenium client compatibility matrix

---

src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java
src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java
src/test/java/io/appium/java_client/service/local/ServerBuilderTest.java

The previous message was not very helpful. Also, I can observe that people don't read full stacktraces anyway

chore: Improve the error message on service startup

---

src/main/java/io/appium/java_client/pagefactory/WindowsBy.java
src/main/java/io/appium/java_client/pagefactory/WindowsFindAll.java
src/main/java/io/appium/java_client/pagefactory/WindowsFindBy.java
src/main/java/io/appium/java_client/pagefactory/WindowsFindByAllSet.java
src/main/java/io/appium/java_client/pagefactory/WindowsFindByChainSet.java
src/main/java/io/appium/java_client/pagefactory/WindowsFindBySet.java
src/main/java/io/appium/java_client/pagefactory/WindowsFindBys.java

These annotations are not used anywhere and we don't need them

chore: Mark Windows page object annotations as deprecated

---

src/main/java/io/appium/java_client/remote/AndroidMobileCapabilityType.java
src/main/java/io/appium/java_client/remote/IOSMobileCapabilityType.java
src/main/java/io/appium/java_client/remote/MobileCapabilityType.java
src/main/java/io/appium/java_client/remote/YouiEngineCapabilityType.java

We only want to have a single place where options are defined.

chore: Deprecate obsolete capabilities constants

---

src/main/java/io/appium/java_client/android/options/context/SupportsShowChromedriverLogOption.java
src/main/java/io/appium/java_client/ios/options/simulator/SupportsCustomSslCertOption.java
src/main/java/io/appium/java_client/ios/options/simulator/SupportsSimulatorTracePointerOption.java

- corrects spelling and semantic errors
- `SupportsCustomSslCertOption` method `setCustomSSLCert()` is now `getCustomSSLCert()` affects `XCUITestOptions`
- `SupportsSimulatorTracePointerOption` method `doesSimulatorTracePointerd()` is now `doesSimulatorTracePointer()` affects `XCUITestOption`
- `SupportsShowChromedriverLogOption` methods `setDhowChromedriverLog(boolean)` and `doesDhowChromedriverLog()` are now `setShowChromedriverLog(boolean)` and `doesShowChromedriverLog()` respectively  affects `ExpressoOptions` and `UIAutomator2Options`
No functional changes

fix: Correct spelling and semantic mistakes in method naming

---

src/main/java/io/appium/java_client/AppiumBy.java
src/main/java/io/appium/java_client/remote/IOSMobileCapabilityType.java
src/main/java/io/appium/java_client/remote/MobileCapabilityType.java

docs(java-client): Added correct url path for the latest appium documentation
'docs(java-client): Added correct url path for the latest appium documentation

docs(java-client): Added correct url path for the latest appium documentation

---

src/main/java/io/appium/java_client/pagefactory/AppiumElementLocator.java
src/main/java/io/appium/java_client/pagefactory/AppiumElementLocatorFactory.java
src/main/java/io/appium/java_client/pagefactory/AppiumFieldDecorator.java
src/main/java/io/appium/java_client/pagefactory/ElementInterceptor.java
src/main/java/io/appium/java_client/pagefactory/WidgetInterceptor.java
src/main/java/io/appium/java_client/pagefactory/WidgetListInterceptor.java
src/main/java/io/appium/java_client/pagefactory/interceptors/InterceptorOfAListOfElements.java
src/main/java/io/appium/java_client/pagefactory/interceptors/InterceptorOfASingleElement.java

This is a quick and poorly tested approach to address https://github.com/appium/appium/discussions/18860#discussioncomment-6731006

fix: Use weak references to elements inside of interceptor objects

---

src/test/java/io/appium/java_client/ios/BaseIOSTest.java

iOS is still unbelievably slow in the CI env. Thus bumping the timeout to 3 minutes

ci: Increase the server startup timeout

---

PULL_REQUEST_TEMPLATE.md
src/main/java/io/appium/java_client/remote/AutomationName.java

Patch AutomationName with Chromium variable.
For running the Chromium driver, we need to set the automation name to Chromium. So, I added this variable to the interface.

chore: patch AutomationName with Chromium

---

build.gradle

Fixes #2012.
`AppiumFluentWait` (which is a part of Appium Java Client API) extends `FluentWait` from `selenium-support` dependency, thus this dependency must be in compile classpath. 
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation:
> Dependencies appearing in the `api` configurations will be transitively exposed to consumers of the library, and as such will appear on the compile classpath of consumers. Dependencies found in the `implementation` configuration will, on the other hand, not be exposed to consumers, and therefore not leak into the consumers' compile classpath.

fix: Change scope of `selenium-support` dependency to `compile`

---

src/main/java/io/appium/java_client/AppiumClientConfig.java

Noticed the class of return value in `proxy` in AppiumClientConfig should be AppiumClientConfig
`ClientConfig` should be `AppiumClientConfig` as same as other methods in the class

fix: class of proxy method in AppiumClientConfig

---

build.gradle

Selenium will stop java8 support since version 4.14, so it makes sense to limit the range now

chore: Limit the maximum selenium version

---

build.gradle

It turns out it is not used anywhere

chore: Remove the obsolete commons-validator dependency

---

README.md
docs/v8-to-v9-migration-guide.md

docs: Add 8 to 9 migration guide

---

build.gradle

Align Selenium version in test dependencies.

test: Align Selenium version in test dependencies

---

CHANGELOG.md
gradle.properties

v9.0.0 and update release notes

release: v9.0.0 and update release notes

---

src/main/java/io/appium/java_client/pagefactory/AppiumFieldDecorator.java
src/main/java/io/appium/java_client/pagefactory/utils/WebDriverUnpackUtility.java

Related to https://github.com/appium/java-client/issues/2051

fix: Properly unwrap driver instance if the ContextAware object is deeply nested

---

config/checkstyle/appium-style.xml
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/SupportsSpecialEmulatorCommands.java
src/main/java/io/appium/java_client/android/connection/HasNetworkConnection.java
src/main/java/io/appium/java_client/functions/AppiumFunction.java
src/main/java/io/appium/java_client/ios/options/other/SupportsCommandTimeoutsOption.java
src/main/java/io/appium/java_client/serverevents/ServerEvents.java
src/test/java/io/appium/java_client/android/AndroidSearchingTest.java
src/test/java/io/appium/java_client/pagefactory_tests/TimeoutTest.java

- Automate single space separator check, it will help to avoid cases like that: https://github.com/appium/java-client/pull/2054#discussion_r1370816109
- Fix all violations of the new rule

build: Enable Checkstyle SingleSpaceSeparator check

---

src/main/java/io/appium/java_client/functions/ActionSupplier.java
src/main/java/io/appium/java_client/functions/AppiumFunction.java
src/main/java/io/appium/java_client/functions/ExpectedCondition.java

Custom functional interfaces are not needed anymore: Selenium closed all gaps in functional Java support.

refactor: Deprecate custom functional interfaces

---

.github/workflows/gradle.yml

It looks like Android tests are not stable recently. Tried to disable the emulator caching to improve that.

ci: Skip Android emulator caching

---

src/main/java/io/appium/java_client/pagefactory/AppiumFieldDecorator.java

I see cases where users unexpectedly pass null values to AppiumFieldDecorator constructor and then get confused. this change should help to better diagnose such situation

chore: Introduce better constructor argument validation for the AppiumFieldDecorator class

---

build.gradle

JaCoCo `0.8.11` [supports Java 21](https://github.com/jacoco/jacoco/releases/tag/v0.8.11). Version bump will resolve errors from CI like:
```
> Task :test
java.lang.instrument.IllegalClassFormatException: Error while instrumenting sun/util/resources/cldr/provider/CLDRLocaleDataMetaInfo with JaCoCo 0.8.8.202204050719/5dcf34a.
at org.jacoco.agent.rt.internal_b6258fc.CoverageTransformer.transform(CoverageTransformer.java:94)
at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:244)
at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:610)
at java.base/java.lang.ClassLoader.defineClass2(Native Method)
at …
```

build(deps): Bump JaCoCo from `0.8.8` to `0.8.11`

---

.github/workflows/gradle.yml
build.gradle
src/main/java/io/appium/java_client/pagefactory/bys/builder/ByChained.java
src/main/java/io/appium/java_client/pagefactory/interceptors/InterceptorOfAListOfElements.java
src/main/java/io/appium/java_client/pagefactory/interceptors/InterceptorOfASingleElement.java
src/main/java/io/appium/java_client/pagefactory/utils/ProxyFactory.java
src/test/java/io/appium/java_client/pagefactory_tests/AndroidPageObjectTest.java

Adresses https://github.com/appium/java-client/issues/2066

fix: Update hashing and iteration logic of page object items

---

src/main/java/io/appium/java_client/AppiumClientConfig.java

Current toString in  AppiumClientConfig is by ClientConfig. Lets write it as the AppiumClientConfig.
Write current available config as AppiumClientConfig in the string

chore: add toString as AppiumClientConfig

---

src/main/java/io/appium/java_client/proxy/ProxyListenersContainer.java

Listeners are cleaned up lazily, e.g. every time `getListeners` API
is called we also remove garbage-collected items. Although, due to an
unpredictable nature of the garbage collector and no guarantees about the
frequency of getListeners API calls we schedule the below loop to be executed every
minute, and make sure there are no extra references to obsolete listeners
- [] Bugfix (non-breaking change which fixes an issue)

chore: Perform listeners cleanup periodically

---

jitpack.yml

Update Jitpack config to use JDK 11 to build snapshots.
Since the minimum supported Java version is 11.

fix: Use JDK 11 to build Jitpack snapshots

---

src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/remote/SupportsContextSwitching.java
src/main/java/io/appium/java_client/remote/SupportsRotation.java

Closes #2090.
See #2090 and linked issues.

chore: Add non-W3C endpoints remove from Selenium client

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/Location.java
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/android/AndroidDriver.java
src/main/java/io/appium/java_client/android/geolocation/SupportsExtendedGeolocationCommands.java
src/main/java/io/appium/java_client/ios/IOSDriver.java
src/main/java/io/appium/java_client/remote/SupportsLocation.java

Add non-W3C Location-management endpoints deprecated in Selenium client: https://github.com/SeleniumHQ/selenium/pull/13372/files#diff-1af793ae2090a0cb691f1efbb3ee0d2b186c4027c5b441f6f3d55b3663e67ba1

chore: Add non-W3C Location-management endpoints deprecated in Selenium client

---

src/main/java/io/appium/java_client/pagefactory/AppiumElementLocatorFactory.java
src/main/java/io/appium/java_client/pagefactory/WidgetByBuilder.java

fix: Always release annotated element reference from the builder instance

---

src/main/java/io/appium/java_client/proxy/Helpers.java

I assume I've finally found the reason for the extensive memory usage described in https://github.com/appium/java-client/issues/2119
Each proxy class created by ByteBuddy gets automatically cached by the
given class loader. It is important to have a custom cache in order to improve
the performance and to avoid extensive memory usage for our case, where
the amount of instrumented proxy classes we create is low in comparison to the amount
of proxy instances.

fix: Cache dynamic proxy classes created by ByteBuddy

---

src/main/java/io/appium/java_client/ExecuteCDPCommand.java
src/main/java/io/appium/java_client/InteractsWithApps.java
src/main/java/io/appium/java_client/MobileCommand.java
src/main/java/io/appium/java_client/MultiTouchAction.java
src/main/java/io/appium/java_client/TouchAction.java
src/main/java/io/appium/java_client/android/AndroidStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/android/appmanagement/AndroidInstallApplicationOptions.java
src/main/java/io/appium/java_client/android/appmanagement/AndroidRemoveApplicationOptions.java
src/main/java/io/appium/java_client/android/appmanagement/AndroidTerminateApplicationOptions.java
src/main/java/io/appium/java_client/android/geolocation/AndroidGeoLocation.java
src/main/java/io/appium/java_client/android/nativekey/KeyEvent.java
src/main/java/io/appium/java_client/android/nativekey/PressesKey.java
src/main/java/io/appium/java_client/driverscripts/ScriptOptions.java
src/main/java/io/appium/java_client/imagecomparison/BaseComparisonOptions.java
src/main/java/io/appium/java_client/imagecomparison/FeaturesMatchingOptions.java
src/main/java/io/appium/java_client/imagecomparison/OccurrenceMatchingOptions.java
src/main/java/io/appium/java_client/ios/IOSStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/ios/IOSTouchAction.java
src/main/java/io/appium/java_client/mac/Mac2StartScreenRecordingOptions.java
src/main/java/io/appium/java_client/remote/AppiumNewSessionCommandPayload.java
src/main/java/io/appium/java_client/remote/SupportsLocation.java
src/main/java/io/appium/java_client/screenrecording/BaseScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/BaseStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/screenrecording/ScreenRecordingUploadOptions.java
src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java
src/main/java/io/appium/java_client/windows/WindowsStartScreenRecordingOptions.java

Public API based on Guava Collections API is not changed (it's already deprecated): https://github.com/appium/java-client/blob/79c6c0ce87cabc8ca5cfd3f047083a43203f5915/src/main/java/io/appium/java_client/MobileCommand.java#L437-L471

refactor: Replace private usages of Guava Collections API with Java Collections API

---

src/main/java/io/appium/java_client/internal/filters/AppiumUserAgentFilter.java
src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java
src/test/java/io/appium/java_client/internal/AppiumUserAgentFilterTest.java

Remove usages of Guava's `@VisibleForTesting` annotation.

refactor: Remove usages of Guava's `@VisibleForTesting`

---

build.gradle
src/main/java/io/appium/java_client/android/geolocation/AndroidGeoLocation.java
src/test/java/io/appium/java_client/android/geolocation/AndroidGeoLocationTest.java

Fix building of Android geo location parameters: this is a fix for regression issue introduced in #2136.

fix: Fix building of Android geo location parameters

---

src/main/java/io/appium/java_client/android/geolocation/AndroidGeoLocation.java
src/main/java/io/appium/java_client/android/nativekey/KeyEvent.java

- fix broken `KeyEvent`
After the last change in `KeyEvent` class, it's impossible to use the key event, because the following code always throws an exception:
```          
ofNullable(this.keyCode)
.map(x -> map.put("keycode", x))
.orElseThrow(() -> new IllegalStateException("The key code must be set"));
```
since `map.put()` returns null for new key.

fix: usage of Optional.orElseThrow after Map.put

---

.github/workflows/gradle-wrapper-validation.yml

https://github.com/gradle/wrapper-validation-action/releases/tag/v3.3.0:
As of v3 this action has been deprecated by gradle/actions/wrapper-validation. Any workflow that uses gradle/wrapper-validation-action@v3 will transparently delegate to gradle/actions/wrapper-validation@v3.

ci: Use non-deprecated GH action for Gradle wrapper validation

---

src/main/java/io/appium/java_client/ComparesImages.java
src/main/java/io/appium/java_client/imagecomparison/ComparisonResult.java
src/main/java/io/appium/java_client/imagecomparison/FeaturesMatchingResult.java
src/main/java/io/appium/java_client/imagecomparison/OccurrenceMatchingResult.java
src/main/java/io/appium/java_client/imagecomparison/SimilarityMatchingResult.java

Addresses https://discuss.appium.io/t/appium-image-comparison-with-multiple-result/

fix: Properly represent FeaturesMatchingResult model if `multiple` option is enabled

---

src/main/java/io/appium/java_client/android/CanReplaceElementValue.java

Same as in https://github.com/appium/java-client/pull/2162, just with CLA signed

fix: Correct extension name for `mobile: replaceElementValue`

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java
src/main/java/io/appium/java_client/remote/AppiumNewSessionCommandPayload.java
src/main/java/io/appium/java_client/remote/AppiumProtocolHandshake.java

The original ProtocolHandshake class only supports W3C protocol now. There is no need to hack it anymore

fix: Deprecate AppiumProtocolHandshake class

---

src/main/java/io/appium/java_client/CommandExecutionHelper.java
src/main/java/io/appium/java_client/clipboard/HasClipboard.java

Based on https://github.com/appium/appium-uiautomator2-driver/pull/800 and https://github.com/appium/appium-xcuitest-driver/pull/2418

chore: Add mobile: replacements to clipboard API wrappers

---

src/main/java/io/appium/java_client/android/ListensToLogcatMessages.java
src/main/java/io/appium/java_client/ios/ListensToSyslogMessages.java

feat: Add ability to use secure WebSocket to listen Logcat messages

---

CHANGELOG.md
gradle.properties

release: v9.3.0

---

src/e2eFlutterTest/java/io/appium/java_client/android/CommandTest.java
src/main/java/io/appium/java_client/flutter/commands/ScrollParameter.java

This PR address the issue https://github.com/AppiumTestDistribution/appium-flutter-integration-driver/issues/88

fix: Scroll issue in flutter integration driver

---

.github/workflows/gradle.yml

This should speed up iOS testing a bit, since we will build WDA for the same device we going to test on.
from https://discuss.appium.io/t/web-driver-agent-issues-with-wda-startup-time/41544/3 and https://github.com/appium/appium-xcuitest-driver/pull/2475 and

chore: build wda for specific device on CI

---

src/main/java/io/appium/java_client/AppiumDriver.java
src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java

Fix compatibility with latest Selenium snapshots.
Recently Selenium team has introduced an update for Appium client adding ability to get `additionalCommands` in `HttpCommandExecutor`: https://github.com/SeleniumHQ/selenium/commit/59aa1a0b5128fcd5e12fe918fd109d443e9f5586.
But since new method is `public` and the same Appium method in `AppiumCommandExecutor.java` is `protected`, this collision introduces an error at the build stage:
```
/Users/runner/work/java-client/java-client/src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java:136: error: getAdditionalCommands() in AppiumCommandExecutor cannot override getAdditionalCommands() in HttpCommandExecutor
protected Map<String, CommandInfo> …
```

fix: Fix compatibility with latest Selenium snapshots

---

src/e2eIosTest/java/io/appium/java_client/ios/IOSBiDiTest.java

These tests should work now after Appium 2.14 is released. We should also create a similar set of tests for UIA2 driver

test: Reenable BiDi logging tests for iOS

---

src/main/java/io/appium/java_client/android/options/adb/SupportsLogcatFilterSpecsOption.java

Addresses https://github.com/appium/java-client/issues/2257

fix: Update the definition of 'logcatFilterSpecs' option

---

src/main/java/io/appium/java_client/proxy/Helpers.java
src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/combined/CombinedWidgetTest.java

Fix for https://github.com/appium/java-client/issues/2247
Expanded test asserts in CombinedWidgetTest, happy to move if better place.

fix: Use WeakHashMap for caching proxy classes 

---

README.md

This PR replaces the deprecated `new URL(String)` constructor with `URI(String).toURL()` in the AndroidDriver initialization code. The `new URL(String)` constructor has been deprecated in Java 20, and this change ensures compatibility with newer Java versions while improving security and consistency in URL handling. 
https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/net/URL.html
About …

fix: update README by replacing the deprecated new URL(String) with URI(String).toURL()

---

build.gradle

Fix the build: fix: add explicit dependency on JSR 305 annotations library.
The annotations `javax.annotation.Nonnull` and `javax.annotation.Nullable` used in the codebase came from library `com.google.code.findbugs:jsr305`. This library was a dependency of `com.google.guava:guava`, which in its turn is a depedendency of Selenium. But `jsr305` dependency was removed in Guava `33.4.3` (https://github.com/google/guava/issues/2960), and Guava was bumped from `33.4.0` to `33.4.5` in Selenium (https://github.com/SeleniumHQ/selenium/commit/ced5b224afaf19bce239fd17d11f026570ff14b3). As the result `com.google.code.findbugs:jsr305` is not present in classpath anymore and lead to build failures: …

fix: Add explicit dependency on JSR 305 annotations library

---

src/test/java/io/appium/java_client/pagefactory_tests/widget/tests/AbstractStubWebDriver.java

The PR addresses the latest breaking changes in Selenium client: https://github.com/SeleniumHQ/selenium/commit/1cad0cae355a20f0061b0c37154992f7b124f7fe.
- Only unit tests are affected, no new release is required
- The current changes keep compatibility with lower versions of Selenium client. Once the minimum Selenium versions are bumped, the deprecated methods can be gradually removed.

fix: Make unit tests compatible with Selenium 4.33.0+

---

.github/workflows/ci.yml
src/e2eFlutterTest/java/io/appium/java_client/android/BaseFlutterTest.java
src/e2eIosTest/java/io/appium/java_client/ios/AppIOSTest.java
src/e2eIosTest/java/io/appium/java_client/ios/BaseIOSTest.java
src/e2eIosTest/java/io/appium/java_client/ios/BaseIOSWebViewTest.java
src/e2eIosTest/java/io/appium/java_client/ios/BaseSafariTest.java
src/main/java/io/appium/java_client/ios/options/XCUITestOptions.java
src/main/java/io/appium/java_client/ios/options/wda/SupportsPrebuiltWdaPathOption.java
src/main/java/io/appium/java_client/ios/options/wda/SupportsUsePreinstalledWdaOption.java

Similar to https://github.com/appium/ruby_lib_core/pull/625

feat: Use prebuilt WDA package to speed up the CI pipeline

---

.github/workflows/publish.yml
.gitignore
build.gradle
docs/release.md

This pull request updates the publishing process for the project to use JReleaser and revises the corresponding documentation. The most important changes include modifying the GitHub Actions workflow to integrate JReleaser and updating the release guide to reflect the new publishing steps.
* [`.github/workflows/publish.yml`](diffhunk://#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7L21-R28): Replaced Maven-specific environment variables with JReleaser-specific variables and added a new `jreleaserDeploy` step to the workflow.
* [`docs/release.md`](diffhunk://#diff-87479ac9ea16cec5ceafce00b3b049d7d5920cb663afae42901f20e7c4e6705dL17-R20): Updated the release guide to replace manual Sonatype Nexus steps with instructions for using the Maven Central Repository via …

ci: Automated Release to Maven Central Repository using JReleaser

---

README.md

CI workflow badge was broken after this PR https://github.com/appium/java-client/pull/2304 was merged which renamed the workflow from `gradle.yml` to `ci.yml`
I have renamed the flow to ci.yml so the project README now shows the correct CI status.
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on …

docs: updated CI badge to use ci.yml workflow

---

README.md

Currently the maven release badge uses [jirutka/maven-badges](https://github.com/jirutka/maven-badges) which has been archived and moved to [softwaremill/maven-badges](https://github.com/softwaremill/maven-badges). 
I tried using the badge from new implementation  but it does not return the latest version available i.e. 9.5.0
[![Maven Central](https://maven-badges.sml.io/sonatype-central/io.appium/java-client/badge.svg)](https://maven-badges.sml.io/sonatype-central/io.appium/java-client)
```
[![Maven Central](https://maven-badges.sml.io/sonatype-central/io.appium/java-client/badge.svg)](https://maven-badges.sml.io/sonatype-central/io.appium/java-client)
```
I found an alternative solution from [shields.io](https://shields.io/badges/maven-central-version) which seems to be working fine and …

docs: updated maven central release badge to shields.io and central sonatype

---

src/main/java/io/appium/java_client/remote/AppiumCommandExecutor.java
src/test/java/io/appium/java_client/remote/AppiumCommandExecutorTest.java

Make sure `httpClientFactory` in `AppiumCommandExecutor` is not null.
version 9.5.0, code is like below
```java
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability("webSocketUrl", true);
driver = new AndroidDriver(AppiumClientConfig.defaultConfig().baseUri(URI.create(url)), capabilities);
```
throws
```
Exception in thread "main" java.lang.NullPointerException: 
Cannot invoke "org.openqa.selenium.remote.http.HttpClient$Factory.createClient(org.openqa.selenium.remote.http.ClientConfig)"
because the return value of "io.appium.java_client.remote.AppiumCommandExecutor.getHttpClientFactory()" is null
at io.appium.java_client.AppiumDriver.initBiDi(AppiumDriver.java:423)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:344)
at …
```

fix: Possible NPE in initBiDi()

---

CHANGELOG.md
docs/Advanced-By.md
docs/How-to-report-an-issue.md
docs/Page-objects.md
docs/environment.md
src/main/java/io/appium/java_client/AppiumCommandInfo.java
src/main/java/io/appium/java_client/android/nativekey/AndroidKey.java
src/main/java/io/appium/java_client/android/options/adb/SupportsLogcatFilterSpecsOption.java
src/main/java/io/appium/java_client/imagecomparison/ComparisonResult.java

chore: fix typos

---

src/e2eAndroidTest/java/io/appium/java_client/android/AndroidScreenRecordTest.java
src/main/java/io/appium/java_client/HasBrowserCheck.java
src/main/java/io/appium/java_client/android/AndroidMobileCommandHelper.java
src/main/java/io/appium/java_client/android/HasAndroidClipboard.java
src/main/java/io/appium/java_client/android/SupportsSpecialEmulatorCommands.java
src/main/java/io/appium/java_client/clipboard/HasClipboard.java
src/main/java/io/appium/java_client/driverscripts/ScriptOptions.java
src/main/java/io/appium/java_client/gecko/options/SupportsVerbosityOption.java
src/main/java/io/appium/java_client/internal/filters/AppiumIdempotencyFilter.java
src/main/java/io/appium/java_client/internal/filters/AppiumUserAgentFilter.java
src/main/java/io/appium/java_client/ios/IOSStartScreenRecordingOptions.java
src/main/java/io/appium/java_client/ios/options/simulator/SupportsSimulatorPasteboardAutomaticSyncOption.java
src/main/java/io/appium/java_client/pagefactory/OverrideWidgetReader.java
src/main/java/io/appium/java_client/pagefactory/utils/WebDriverUnpackUtility.java
src/main/java/io/appium/java_client/remote/SupportsRotation.java
src/main/java/io/appium/java_client/remote/options/SupportsOrientationOption.java
src/main/java/io/appium/java_client/remote/options/SupportsPageLoadStrategyOption.java
src/main/java/io/appium/java_client/remote/options/UnhandledPromptBehavior.java
src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java
src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java

For example, if the system default locale is Turkish ("tr_TR"), then `ClipboardContentType.PLAINTEXT` argument gets converted to "plaıntext", not "plaintext".
1. Replace `toLowerCase()` -> `toLowerCase(ROOT)`
2. Replace `toUpperCase()` -> `toUpperCase(ROOT)`
"ROOT" is a specific locale that at least works well for latin letters (that are used in content types, enum names etc.)

fix: avoid using system default locale
